/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C12_RUNTIMEEXCEPTION_H__
#define __C12_RUNTIMEEXCEPTION_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C12_RUNTIMEEXCEPTION_ID ((class_id_t)12)

/* object data */
typedef struct {
/* c12_RuntimeException */
/* c11_Exception */
/* c10_Throwable */
	object_pointer c10f1_message;
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c10_Throwable */
/* c11_Exception */
/* c12_RuntimeException */
} c12_RuntimeException_t;
#define C12_RUNTIMEEXCEPTION_OBJ(_obj_) ((c12_RuntimeException_t*)((object_pointer*)(_obj_)-1))
#define ACCFIELD_C12_RUNTIMEEXCEPTION_C10F1_MESSAGE(_obj_) (C12_RUNTIMEEXCEPTION_OBJ(_obj_)->c10f1_message)
#define KESO_ALLOC_C12_RUNTIMEEXCEPTION() KESO_ALLOC(C12_RUNTIMEEXCEPTION_ID,sizeof(c12_RuntimeException_t),1)
#define KESO_ALLOC_STACK_C12_RUNTIMEEXCEPTION(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C12_RUNTIMEEXCEPTION_ID,sizeof(c12_RuntimeException_t),1)
#define KESO_ALLOC_INLINE_C12_RUNTIMEEXCEPTION() KESO_ALLOC(C12_RUNTIMEEXCEPTION_ID,sizeof(c12_RuntimeException_t),1)

/* class methods prototypes */



#endif /* !defined(__C12_RUNTIMEEXCEPTION_H__) */
