/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C13_STRINGINDEXOUTOFBOUNDSEXCEPTION_H__
#define __C13_STRINGINDEXOUTOFBOUNDSEXCEPTION_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C13_STRINGINDEXOUTOFBOUNDSEXCEPTION_ID ((class_id_t)13)

/* object data */
typedef struct {
/* c13_StringIndexOutOfBoundsException */
/* c12_RuntimeException */
/* c11_Exception */
/* c10_Throwable */
	object_pointer c10f1_message;
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c10_Throwable */
/* c11_Exception */
/* c12_RuntimeException */
/* c13_StringIndexOutOfBoundsException */
} c13_StringIndexOutOfBoundsException_t;
#define C13_STRINGINDEXOUTOFBOUNDSEXCEPTION_OBJ(_obj_) ((c13_StringIndexOutOfBoundsException_t*)((object_pointer*)(_obj_)-1))
#define ACCFIELD_C13_STRINGINDEXOUTOFBOUNDSEXCEPTION_C10F1_MESSAGE(_obj_) (C13_STRINGINDEXOUTOFBOUNDSEXCEPTION_OBJ(_obj_)->c10f1_message)
#define KESO_ALLOC_C13_STRINGINDEXOUTOFBOUNDSEXCEPTION() KESO_ALLOC(C13_STRINGINDEXOUTOFBOUNDSEXCEPTION_ID,sizeof(c13_StringIndexOutOfBoundsException_t),1)
#define KESO_ALLOC_STACK_C13_STRINGINDEXOUTOFBOUNDSEXCEPTION(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C13_STRINGINDEXOUTOFBOUNDSEXCEPTION_ID,sizeof(c13_StringIndexOutOfBoundsException_t),1)
#define KESO_ALLOC_INLINE_C13_STRINGINDEXOUTOFBOUNDSEXCEPTION() KESO_ALLOC(C13_STRINGINDEXOUTOFBOUNDSEXCEPTION_ID,sizeof(c13_StringIndexOutOfBoundsException_t),1)

/* class methods prototypes */



#endif /* !defined(__C13_STRINGINDEXOUTOFBOUNDSEXCEPTION_H__) */
