/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c14_Error.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 1 c14_Error_m1__init_
 *
 * c1_Object_m2_hashCode
 * (valid java/lang/Object, "This method must be implemented by the runtime system." java/lang/String)
 *
 * total (valid java/lang/Object, "This method must be implemented by the runtime system." java/lang/String)
 */

/* c14_Error_m1__init_ #non_blocking */
/* java/lang/Error.<init>(Ljava/lang/String;)V */

void c14_Error_m1__init_(object_pointer obj0, object_pointer obj1)
{
	
/* c14_Error_m1__init__B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 34:   super(s);
/==============================================================*/

	/* goto c14_Error_m1__init__B7 */

	
/* c14_Error_m1__init__B7:  Pred:  0 No: 3 done */
	
/*==============================================================/
| 35:  }
/==============================================================*/

	return;

}

