/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c15_StringBuilder.h"
#include "char_array.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 4 c15_StringBuilder_m3__init_
 *
 * c8_DebugOut_m4__clinit_
 * (valid java/lang/StringBuilder)
 *
 * c7_HelloWorld_m2_run
 * (valid java/lang/StringBuilder)
 *
 * c7_HelloWorld_m2_run
 * (valid java/lang/StringBuilder)
 *
 * c7_HelloWorld_m2_run
 * (valid java/lang/StringBuilder)
 *
 * total (valid java/lang/StringBuilder)
 */

/* c15_StringBuilder_m3__init_ #non_blocking */
/* java/lang/StringBuilder.<init>()V */

void c15_StringBuilder_m3__init_(object_pointer obj0)
{
	object_pointer obj2;
	
/* c15_StringBuilder_m3__init__B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 45:   this(minIncrease);
| 46:  }
/==============================================================*/

	obj2 = keso_alloc_char_array(0x8);
	(ACCFIELD_C15_STRINGBUILDER_C15F1_DATA(obj0)) = (object_pointer)obj2;
	(ACCFIELD_C15_STRINGBUILDER_C15F2_LENGTH(obj0)) = (jint)(0);
	/* goto c15_StringBuilder_m3__init__B8 */

	
/* c15_StringBuilder_m3__init__B8:  Pred:  0 No: 4 done */

	return;

}

