/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c15_StringBuilder.h"
#include "char_array.h"
#include "keso_exceptions.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 3 c15_StringBuilder_m4_append
 *
 * c20_Integer_m1_toString
 * (valid java/lang/StringBuilder, 48)
 *
 * c20_Integer_m1_toString
 * (valid java/lang/StringBuilder, int)
 *
 * c20_Integer_m1_toString
 * (valid java/lang/StringBuilder, 45)
 *
 * total (valid java/lang/StringBuilder, unknown)
 */

/* c15_StringBuilder_m4_append #non_blocking */
/* java/lang/StringBuilder.append(C)Ljava/lang/StringBuilder; */

object_pointer c15_StringBuilder_m4_append(object_pointer obj0, jint i1)
{
	jint i3_0;
	object_pointer obj4_0;
	jint i3_1;
	jint i3_2;
	
/* c15_StringBuilder_m4_append_B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 106:   ensureCapacity(length + 1);
| 107:   data[length] = c;
/==============================================================*/

	i3_0 = ((ACCFIELD_C15_STRINGBUILDER_C15F2_LENGTH(obj0))+0x1);
	c15_StringBuilder_m7_ensureCapacity(obj0, i3_0);
	obj4_0 = (ACCFIELD_C15_STRINGBUILDER_C15F1_DATA(obj0));
	i3_1 = (ACCFIELD_C15_STRINGBUILDER_C15F2_LENGTH(obj0));
				KESO_CHECK_CASTORE_NULLPOINTER(obj4_0,"c15_StringBuilder_m4_append",19, 10);

	
/* z54_c15_StringBuilder_m4_append_B19:  Pred:  0 No: 3 done */
	
/*==============================================================/
| 108:   length++;
| 109:   return this;
/==============================================================*/

				KESO_CHECK_CASTORE_ARRAY_NOTNULL(obj4_0,i3_1,"c15_StringBuilder_m4_append",19, 11);
	CHAR_ARRAY_LEA(obj4_0, i3_1) = i1;
	i3_2 = ((ACCFIELD_C15_STRINGBUILDER_C15F2_LENGTH(obj0))+0x1);
	(ACCFIELD_C15_STRINGBUILDER_C15F2_LENGTH(obj0)) = (jint)i3_2;
	/* goto c15_StringBuilder_m4_append_B33 */

	
/* c15_StringBuilder_m4_append_B33:  Pred:  7 No: 4 done */

	return (object_pointer)obj0;

}

