/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c15_StringBuilder.h"
#include "c19_Long.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 3 c15_StringBuilder_m10_append
 *
 * c7_HelloWorld_m2_run
 * (valid java/lang/StringBuilder, long)
 *
 * c7_HelloWorld_m2_run
 * (valid java/lang/StringBuilder, long)
 *
 * c7_HelloWorld_m2_run
 * (valid java/lang/StringBuilder, long)
 *
 * total (valid java/lang/StringBuilder, long)
 */

/* c15_StringBuilder_m10_append #non_blocking */
/* java/lang/StringBuilder.append(J)Ljava/lang/StringBuilder; */

object_pointer c15_StringBuilder_m10_append(object_pointer obj0, jlong l1)
{
	object_pointer obj4_0;
	object_pointer obj3_0;
	
/* c15_StringBuilder_m10_append_B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 162:   return append(Long.toString(l));
/==============================================================*/

	obj4_0 = c19_Long_m1_toString(l1);
	obj3_0 = c15_StringBuilder_m1_append(obj0, obj4_0);
	/* goto c15_StringBuilder_m10_append_B10 */

	
/* c15_StringBuilder_m10_append_B10:  Pred:  0 No: 3 done */

	return (object_pointer)obj3_0;

}

