/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c15_StringBuilder.h"
#include "c23_String.h"
#include "keso_exceptions.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 11 c15_StringBuilder_m1_append
 *
 * c8_DebugOut_m2_println
 * (valid java/lang/StringBuilder, "
" java/lang/String)
 *
 * c8_DebugOut_m6_println
 * (valid java/lang/StringBuilder, ?null java/lang/Object)
 *
 * c15_StringBuilder_m1_append
 * (valid java/lang/Object, "null" java/lang/String)
 *
 * c15_StringBuilder_m10_append
 * (valid java/lang/Object, ?null java/lang/String)
 *
 * c30_DebugOutPrintStream_m7_print
 * (valid java/lang/StringBuilder, ?null java/lang/Object)
 *
 * c7_HelloWorld_m2_run
 * (valid java/lang/StringBuilder, "Runtime " java/lang/String)
 *
 * c7_HelloWorld_m2_run
 * (valid java/lang/StringBuilder, " ns" java/lang/String)
 *
 * c7_HelloWorld_m2_run
 * (valid java/lang/StringBuilder, "	start: " java/lang/String)
 *
 * c7_HelloWorld_m2_run
 * (valid java/lang/StringBuilder, " ns" java/lang/String)
 *
 * c7_HelloWorld_m2_run
 * (valid java/lang/StringBuilder, "	stop: " java/lang/String)
 *
 * c7_HelloWorld_m2_run
 * (valid java/lang/StringBuilder, " ns" java/lang/String)
 *
 * total (valid java/lang/Object, ?null java/lang/Object)
 */

/* c15_StringBuilder_m1_append #non_blocking */
/* java/lang/StringBuilder.append(Ljava/lang/String;)Ljava/lang/StringBuilder; */

object_pointer c15_StringBuilder_m1_append(object_pointer obj0, object_pointer obj1)
{
	jint i4_0;
	object_pointer obj5_0;
	jint i6_0;
	jint i4_1;
	jint i15;
	object_pointer obj17;
	
/* c15_StringBuilder_m1_append_B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 130:   if (str == null)
/==============================================================*/

	if (obj1!=(object_pointer) (void *) 0) goto z47_c15_StringBuilder_m1_append_B4;

	
/* z46_c15_StringBuilder_m1_append_B10:  Pred:  0 No: 3 done */
	
/*==============================================================/
| 131:    return append("null");
/==============================================================*/

	obj0 = c15_StringBuilder_m1_append(obj0, ((object_pointer) ((object_pointer*) &str1+1)));
	goto c15_StringBuilder_m1_append_B53;

	
z47_c15_StringBuilder_m1_append_B4: /* Pred:  0 No: 6 done */
	
/*==============================================================/
: 132: 
| 133:   int n = str.length();
/==============================================================*/

	obj17 = (ACCFIELD_C23_STRING_C23F1_VALUE(obj1));
				KESO_CHECK_ARRAYLENGTH_NULLPOINTER(obj17,"c15_StringBuilder_m1_append",12, 9);

	
/* z48_c15_StringBuilder_m1_append_B5:  Pred:  11 No: 7 done */
	
/*==============================================================/
| 134:   ensureCapacity(length + n);
| 135:   str.getChars(0, n, data, length);
| 136:   length += n;
: 137: 
| 138:   return this;
/==============================================================*/

	i15 = KESO_GET_ARRAY_LENGTH(obj17);
	i4_0 = ((ACCFIELD_C15_STRINGBUILDER_C15F2_LENGTH(obj0))+i15);
	c15_StringBuilder_m7_ensureCapacity(obj0, i4_0);
	obj5_0 = (ACCFIELD_C15_STRINGBUILDER_C15F1_DATA(obj0));
	i6_0 = (ACCFIELD_C15_STRINGBUILDER_C15F2_LENGTH(obj0));
	c23_String_m3_getChars(obj1, i15, obj5_0, i6_0);
	i4_1 = ((ACCFIELD_C15_STRINGBUILDER_C15F2_LENGTH(obj0))+i15);
	(ACCFIELD_C15_STRINGBUILDER_C15F2_LENGTH(obj0)) = (jint)i4_1;
	/* goto c15_StringBuilder_m1_append_B53 */

	
c15_StringBuilder_m1_append_B53: /* Pred:  4 4 No: 4 done */

	return (object_pointer)obj0;

}

