/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C15_STRINGBUILDER_H__
#define __C15_STRINGBUILDER_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C15_STRINGBUILDER_ID ((class_id_t)15)

/* object data */
typedef struct {
/* c15_StringBuilder */
	object_pointer c15f1_data;
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
	jint c15f2_length;
/* c15_StringBuilder */
} c15_StringBuilder_t;
#define C15_STRINGBUILDER_OBJ(_obj_) ((c15_StringBuilder_t*)((object_pointer*)(_obj_)-1))
#define ACCFIELD_C15_STRINGBUILDER_C15F1_DATA(_obj_) (C15_STRINGBUILDER_OBJ(_obj_)->c15f1_data)
#define ACCFIELD_C15_STRINGBUILDER_C15F2_LENGTH(_obj_) (C15_STRINGBUILDER_OBJ(_obj_)->c15f2_length)
#define KESO_ALLOC_C15_STRINGBUILDER() KESO_ALLOC(C15_STRINGBUILDER_ID,sizeof(c15_StringBuilder_t),1)
#define KESO_ALLOC_STACK_C15_STRINGBUILDER(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C15_STRINGBUILDER_ID,sizeof(c15_StringBuilder_t),1)
#define KESO_ALLOC_INLINE_C15_STRINGBUILDER() KESO_ALLOC(C15_STRINGBUILDER_ID,sizeof(c15_StringBuilder_t),1)

/* class methods prototypes */
/* c15_StringBuilder_m7_ensureCapacity #non_blocking */
/* ensureCapacity(I)V */
void c15_StringBuilder_m7_ensureCapacity(object_pointer obj0, jint i1);
/* c15_StringBuilder_m3__init_ #non_blocking */
/* <init>()V */
void c15_StringBuilder_m3__init_(object_pointer obj0);
/* c15_StringBuilder_m9_toString #non_blocking */
/* toString()Ljava/lang/String; */
object_pointer c15_StringBuilder_m9_toString(object_pointer obj0);
/* c15_StringBuilder_m1_append #non_blocking */
/* append(Ljava/lang/String;)Ljava/lang/StringBuilder; */
object_pointer c15_StringBuilder_m1_append(object_pointer obj0, object_pointer obj1);
/* c15_StringBuilder_m10_append #non_blocking */
/* append(J)Ljava/lang/StringBuilder; */
object_pointer c15_StringBuilder_m10_append(object_pointer obj0, jlong l1);
/* c15_StringBuilder_m4_append #non_blocking */
/* append(C)Ljava/lang/StringBuilder; */
object_pointer c15_StringBuilder_m4_append(object_pointer obj0, jint i1);



#endif /* !defined(__C15_STRINGBUILDER_H__) */
