/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c15_StringBuilder.h"
#include "char_array.h"
#include "keso_exceptions.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 3 c15_StringBuilder_m7_ensureCapacity
 *
 * c8_DebugOut_m2_println
 * (valid java/lang/StringBuilder, 0)
 *
 * c15_StringBuilder_m1_append
 * (valid java/lang/Object, int)
 *
 * c15_StringBuilder_m4_append
 * (valid java/lang/Object, int)
 *
 * total (valid java/lang/Object, unknown)
 */

/* c15_StringBuilder_m7_ensureCapacity #non_blocking */
/* java/lang/StringBuilder.ensureCapacity(I)V */

void c15_StringBuilder_m7_ensureCapacity(object_pointer obj0, jint i1)
{
	object_pointer obj5_0;
	object_pointer obj4_0;
	jint i9_0;
	jint i29;
	jint i31;
	jint i37;
	
/* c15_StringBuilder_m7_ensureCapacity_B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 53:   if (data.length >= minimumCapacity) return;
/==============================================================*/

	obj5_0 = (ACCFIELD_C15_STRINGBUILDER_C15F1_DATA(obj0));
				KESO_CHECK_ARRAYLENGTH_NULLPOINTER(obj5_0,"c15_StringBuilder_m7_ensureCapacity",4, 6);

	
/* z35_c15_StringBuilder_m7_ensureCapacity_B6:  Pred:  0 No: 3 done */

	if (KESO_GET_ARRAY_LENGTH(obj5_0)<i1) goto z36_c15_StringBuilder_m7_ensureCapacity_B19;

	
/* c15_StringBuilder_m7_ensureCapacity_B9:  Pred:  4 No: 4 done */

	goto c15_StringBuilder_m7_ensureCapacity_B58;

	
z36_c15_StringBuilder_m7_ensureCapacity_B19: /* Pred:  4 No: 7 done */
	
/*==============================================================/
| 54:   int d = Math.min(maxIncrease,data.length << 1);
/==============================================================*/

	i29 = (KESO_GET_ARRAY_LENGTH(obj5_0)<<1);
	if (0x20>=i29) goto z5_c26_Math_m1_min_B10;

	
/* z4_c26_Math_m1_min_B5:  Pred:  10 No: 8 done */

	i29 = 0x20;
	/* goto z5_c26_Math_m1_min_B10 */

	
z5_c26_Math_m1_min_B10: /* Pred:  5 10 No: 9 done */
	
/*==============================================================/
| 55:   int n = Math.max(minimumCapacity, d);
/==============================================================*/

	if (i1>=i29) goto z11_c26_Math_m2_max_B9;

	
/* z9_c26_Math_m2_max_B5:  Pred:  10 No: 10 done */

	goto z37_c26_Math_m2_max_B32;

	
z11_c26_Math_m2_max_B9: /* Pred:  10 No: 20 done */

	i29 = i1;

	
z37_c26_Math_m2_max_B32: /* Pred:  9 5 No: 12 done */
	
/*==============================================================/
| 56:   char[] buff = new char[n];
| 57:   copy_chars(data, 0, buff, 0, data.length);
/==============================================================*/

	obj4_0 = keso_alloc_char_array(i29);
	i9_0 = KESO_GET_ARRAY_LENGTH(obj5_0);
	i31 = (0);

	
z14_c15_StringBuilder_m8_copy_chars_B3: /* Pred:  10 10 No: 14 done */

	if (i31>=i9_0) goto z41_c15_StringBuilder_m8_copy_chars_B53;

	
/* z39_c15_StringBuilder_m8_copy_chars_B21:  Pred:  3 No: 16 done */

				KESO_CHECK_CALOAD_ARRAY_NOTNULL(obj5_0,i31,"c15_StringBuilder_m7_ensureCapacity",47, 7);
	i37 = CHAR_ARRAY_ALOAD(obj5_0, i31);
				KESO_CHECK_CASTORE_ARRAY_NOTNULL(obj4_0,i31,"c15_StringBuilder_m7_ensureCapacity",47, 8);
	CHAR_ARRAY_LEA(obj4_0, i31) = i37;
	i31 = (i31+0x1);
	goto z14_c15_StringBuilder_m8_copy_chars_B3;

	
z41_c15_StringBuilder_m8_copy_chars_B53: /* Pred:  3 No: 19 done */
	
/*==============================================================/
| 58:   data = buff;
| 59:  }
/==============================================================*/

	(ACCFIELD_C15_STRINGBUILDER_C15F1_DATA(obj0)) = (object_pointer)obj4_0;
	/* goto c15_StringBuilder_m7_ensureCapacity_B58 */

	
c15_StringBuilder_m7_ensureCapacity_B58: /* Pred:  28 9 No: 5 done */

	return;

}

