/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C16_A_H__
#define __C16_A_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C16_A_ID ((class_id_t)16)

/* object data */
typedef struct {
/* c16_A */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c16_A */
} c16_A_t;
#define C16_A_OBJ(_obj_) ((c16_A_t*)(_obj_))

/* class methods prototypes */
/* c16_A_m1_m1 #non_blocking */
/* m1()V */
void c16_A_m1_m1(object_pointer obj0);



#endif /* !defined(__C16_A_H__) */
