/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C17_B_H__
#define __C17_B_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C17_B_ID ((class_id_t)17)

/* object data */
typedef struct {
/* c17_B */
/* c16_A */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c16_A */
/* c17_B */
} c17_B_t;
#define C17_B_OBJ(_obj_) ((c17_B_t*)(_obj_))
#define KESO_ALLOC_C17_B() KESO_ALLOC(C17_B_ID,sizeof(c17_B_t),0)
#define KESO_ALLOC_STACK_C17_B(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C17_B_ID,sizeof(c17_B_t),0)
#define KESO_ALLOC_INLINE_C17_B() KESO_ALLOC(C17_B_ID,sizeof(c17_B_t),0)

/* class methods prototypes */



#endif /* !defined(__C17_B_H__) */
