/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C18_NUMBER_H__
#define __C18_NUMBER_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C18_NUMBER_ID ((class_id_t)18)

/* object data */
typedef struct {
/* c18_Number */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c18_Number */
} c18_Number_t;
#define C18_NUMBER_OBJ(_obj_) ((c18_Number_t*)(_obj_))

/* class methods prototypes */



#endif /* !defined(__C18_NUMBER_H__) */
