/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c19_Long.h"
#include "c21_Character.h"
#include "c23_String.h"
#include "char_array.h"
#include "keso_exceptions.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 1 c19_Long_m2_toString
 *
 * c19_Long_m1_toString
 * (long, 10)
 *
 * total (long, 10)
 */

/* c19_Long_m2_toString #non_blocking */
/* java/lang/Long.toString(JI)Ljava/lang/String; */

object_pointer c19_Long_m2_toString(jlong l0, jint i2)
{
	object_pointer obj3_0;
	jint i5_2;
	jint i6_0;
	jint i10_0;
	jint i4_5;
	jint i9_1;
	object_pointer obj7_2;
	
/* c19_Long_m2_toString_B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 115:   final char buffer[] = new char[20]; // max len (radix 10!!!): -9223372036854775808
: 116:   int i=20;
: 117: 
: 118: //  buffer[--i]='L';
| 119:   if (value == 0) {
/==============================================================*/

	obj3_0 = keso_alloc_char_array(0x14);
	if ((l0-(0LL))!=(0)) goto c19_Long_m2_toString_B40;

	
/* z5_c19_Long_m2_toString_B23:  Pred:  0 No: 4 done */
	
/*==============================================================/
| 120:    buffer[--i]='0';
| 121:    return new String(buffer, i, 20-i);
/==============================================================*/

		CHAR_ARRAY_LEA(obj3_0, 0x13) = 0x30;
	obj7_2 = KESO_ALLOC_C23_STRING();
	c23_String_m1__init_(obj7_2, obj3_0, 0x13, 0x1);
	goto c19_Long_m2_toString_B120;

	
c19_Long_m2_toString_B40: /* Pred:  0 No: 7 done */
	
/*==============================================================/
: 122:   }
: 123: 
: 124:   boolean isNegative = false;
| 125:   if( value < 0 ){
/==============================================================*/

	i4_5 = 0x14;
	i5_2 = (0);
	if ((l0-(0LL))>=(0)) goto c19_Long_m2_toString_B55;

	
/* c19_Long_m2_toString_B49:  Pred:  40 No: 8 done */
	
/*==============================================================/
: 126:    isNegative = true;
| 127:    value = -value;
/==============================================================*/

	l0 = (l0* -1);
	i4_5 = 0x14;
	i5_2 = 0x1;

	
c19_Long_m2_toString_B55: /* Pred:  40 61 49 No: 9 done */
	
/*==============================================================/
: 128:   }
: 129: 
| 130:   while (value > 0) {
/==============================================================*/

	if ((l0-(0LL))<=(0)) goto c19_Long_m2_toString_B89;

	
/* c19_Long_m2_toString_B61:  Pred:  55 No: 10 done */
	
/*==============================================================/
| 131:    int r = (int)(value % radix);
| 132:    buffer[--i]=Character.forDigit(r, radix);
| 133:    value /= radix;
| 134:   }
/==============================================================*/

	i6_0 = ((jint)(l0%(10LL)));
	i4_5 = (i4_5+(-1));
	i10_0 = c21_Character_m2_forDigit(i6_0, 0xa);
				KESO_CHECK_CASTORE_ARRAY_KNOWNBOUNDS(20,i4_5,"c19_Long_m2_toString",80, 14);
	CHAR_ARRAY_LEA(obj3_0, i4_5) = i10_0;
	l0 = (l0/(10LL));
	goto c19_Long_m2_toString_B55;

	
c19_Long_m2_toString_B89: /* Pred:  55 No: 12 done */
	
/*==============================================================/
: 135: 
| 136:   if (isNegative) buffer[--i]='-';
/==============================================================*/

	if (i5_2==(0)) goto c19_Long_m2_toString_B103;

	
/* c19_Long_m2_toString_B94:  Pred:  89 No: 13 done */

	i4_5 = (i4_5+(-1));
		CHAR_ARRAY_LEA(obj3_0, i4_5) = 0x2d;

	
c19_Long_m2_toString_B103: /* Pred:  89 94 No: 15 done */
	
/*==============================================================/
: 137: 
| 138:   return new String(buffer, i, 20-i);
/==============================================================*/

	obj7_2 = KESO_ALLOC_C23_STRING();
	i9_1 = (0x14-i4_5);
	c23_String_m1__init_(obj7_2, obj3_0, i4_5, i9_1);
	/* goto c19_Long_m2_toString_B120 */

	
c19_Long_m2_toString_B120: /* Pred:  103 15 No: 6 done */

	return (object_pointer)obj7_2;

}

