/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c19_Long.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 2 c19_Long_m4__clinit_
 *
 * <kore>
 * ()
 *
 * <kore>
 * ()
 *
 * total ()
 */

/* c19_Long_m4__clinit_ #non_blocking */
/* java/lang/Long.<clinit>()V */

void c19_Long_m4__clinit_(void)
{
	
/* c19_Long_m4__clinit__B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 29:  public static final Class TYPE = Class.getPrimitiveClass("long");
/==============================================================*/

	/* goto c19_Long_m4__clinit__B10 */

	
/* c19_Long_m4__clinit__B10:  Pred:  0 No: 2 done */

	return;

}

