/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c19_Long.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 2 c19_Long_m1_toString
 *
 * c8_DebugOut_m5_println
 * (long)
 *
 * c15_StringBuilder_m10_append
 * (long)
 *
 * total (long)
 */

/* c19_Long_m1_toString #non_blocking */
/* java/lang/Long.toString(J)Ljava/lang/String; */

object_pointer c19_Long_m1_toString(jlong l0)
{
	object_pointer obj2_0;
	
/* c19_Long_m1_toString_B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 111:   return toString(value, 10);
/==============================================================*/

	obj2_0 = c19_Long_m2_toString(l0, 0xa);
	/* goto c19_Long_m1_toString_B8 */

	
/* c19_Long_m1_toString_B8:  Pred:  0 No: 2 done */

	return (object_pointer)obj2_0;

}

