/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c1_Object.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 1 c1_Object_m2_hashCode
 *
 * c7_HelloWorld_m2_run
 * (valid test/B)
 *
 * total (valid test/B)
 */

/* c1_Object_m2_hashCode #non_blocking */
/* java/lang/Object.hashCode()I */

jint c1_Object_m2_hashCode(object_pointer obj0)
{
	/* we use the object address as default hash code */
	return (jint)obj0;
}

