/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c20_Integer.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 2 c20_Integer_m3__clinit_
 *
 * <kore>
 * ()
 *
 * <kore>
 * ()
 *
 * total ()
 */

/* c20_Integer_m3__clinit_ #non_blocking */
/* java/lang/Integer.<clinit>()V */

void c20_Integer_m3__clinit_(void)
{
	
/* c20_Integer_m3__clinit__B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 28:  public static final Class TYPE = Class.getPrimitiveClass("int");
/==============================================================*/

	/* goto c20_Integer_m3__clinit__B10 */

	
/* c20_Integer_m3__clinit__B10:  Pred:  0 No: 2 done */

	return;

}

