/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C20_INTEGER_H__
#define __C20_INTEGER_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C20_INTEGER_ID ((class_id_t)20)

/* object data */
typedef struct {
/* c20_Integer */
/* c18_Number */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c18_Number */
/* c20_Integer */
} c20_Integer_t;
#define C20_INTEGER_OBJ(_obj_) ((c20_Integer_t*)(_obj_))
#define KESO_ALLOC_C20_INTEGER() KESO_ALLOC(C20_INTEGER_ID,sizeof(c20_Integer_t),0)
#define KESO_ALLOC_STACK_C20_INTEGER(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C20_INTEGER_ID,sizeof(c20_Integer_t),0)
#define KESO_ALLOC_INLINE_C20_INTEGER() KESO_ALLOC(C20_INTEGER_ID,sizeof(c20_Integer_t),0)

/* class methods prototypes */
/* c20_Integer_m3__clinit_ #non_blocking */
/* <clinit>()V */
void c20_Integer_m3__clinit_(void);
/* c20_Integer_m1_toString #non_blocking */
/* toString(I)Ljava/lang/String; */
object_pointer c20_Integer_m1_toString(jint i0);



#endif /* !defined(__C20_INTEGER_H__) */
