/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c21_Character.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 2 c21_Character_m2_forDigit
 *
 * c19_Long_m2_toString
 * (int, 10)
 *
 * c20_Integer_m1_toString
 * (int, 10)
 *
 * total (int, 10)
 */

/* c21_Character_m2_forDigit #non_blocking */
/* java/lang/Character.forDigit(II)C */

jchar c21_Character_m2_forDigit(jint i0, jint i1)
{
	jint i2_4;
	
/* c21_Character_m2_forDigit_B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 118:   if(digit < 0 || digit >= radix)
/==============================================================*/

	if (i0<(0)) goto c21_Character_m2_forDigit_B22;

	
/* c21_Character_m2_forDigit_B17:  Pred:  0 No: 6 done */

	if (i0<0xa) goto c21_Character_m2_forDigit_B24;

	
c21_Character_m2_forDigit_B22: /* Pred:  0 17 No: 7 done */
	
/*==============================================================/
| 119:    return MIN_VALUE;
/==============================================================*/

	i2_4 = (0);
	goto c21_Character_m2_forDigit_B46;

	
c21_Character_m2_forDigit_B24: /* Pred:  17 No: 8 done */
	
/*==============================================================/
| 120:   if (digit < 10)
/==============================================================*/

	if (i0>=0xa) goto c21_Character_m2_forDigit_B36;

	
/* c21_Character_m2_forDigit_B30:  Pred:  24 No: 9 done */
	
/*==============================================================/
| 121:    return (char)('0' + digit);
/==============================================================*/

	i2_4 = ((jchar)(i0+0x30));
	goto c21_Character_m2_forDigit_B46;

	
c21_Character_m2_forDigit_B36: /* Pred:  24 No: 10 done */
	
/*==============================================================/
: 122:   else
| 123:    return (char)('a' + digit - 10);
/==============================================================*/

	i2_4 = ((jchar)((i0+0x61)-0xa));
	/* goto c21_Character_m2_forDigit_B46 */

	
c21_Character_m2_forDigit_B46: /* Pred:  22 36 30 No: 4 done */

	return i2_4;

}

