/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C21_CHARACTER_H__
#define __C21_CHARACTER_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C21_CHARACTER_ID ((class_id_t)21)

/* object data */
typedef struct {
/* c21_Character */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c21_Character */
} c21_Character_t;
#define C21_CHARACTER_OBJ(_obj_) ((c21_Character_t*)(_obj_))
#define KESO_ALLOC_C21_CHARACTER() KESO_ALLOC(C21_CHARACTER_ID,sizeof(c21_Character_t),0)
#define KESO_ALLOC_STACK_C21_CHARACTER(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C21_CHARACTER_ID,sizeof(c21_Character_t),0)
#define KESO_ALLOC_INLINE_C21_CHARACTER() KESO_ALLOC(C21_CHARACTER_ID,sizeof(c21_Character_t),0)

/* class methods prototypes */
/* c21_Character_m2_forDigit #non_blocking */
/* forDigit(II)C */
jchar c21_Character_m2_forDigit(jint i0, jint i1);



#endif /* !defined(__C21_CHARACTER_H__) */
