/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C22_CLASS_H__
#define __C22_CLASS_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C22_CLASS_ID ((class_id_t)22)

/* object data */
typedef struct {
/* c22_Class */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c22_Class */
} c22_Class_t;
#define C22_CLASS_OBJ(_obj_) ((c22_Class_t*)(_obj_))
#define KESO_ALLOC_C22_CLASS() KESO_ALLOC(C22_CLASS_ID,sizeof(c22_Class_t),0)
#define KESO_ALLOC_STACK_C22_CLASS(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C22_CLASS_ID,sizeof(c22_Class_t),0)
#define KESO_ALLOC_INLINE_C22_CLASS() KESO_ALLOC(C22_CLASS_ID,sizeof(c22_Class_t),0)

/* class methods prototypes */



#endif /* !defined(__C22_CLASS_H__) */
