/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c25_System.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 1 c25_System_m2_getProperty
 *
 * c7_HelloWorld_m2_run
 * ("ddom1.ttask1.HelloString" java/lang/String, "Hello World!" java/lang/String)
 *
 * total ("ddom1.ttask1.HelloString" java/lang/String, "Hello World!" java/lang/String)
 */

/* c25_System_m2_getProperty #non_blocking */
/* java/lang/System.getProperty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String; */

object_pointer c25_System_m2_getProperty(object_pointer obj0, object_pointer obj1)
{
	object_pointer obj2;
	
/* c25_System_m2_getProperty_B0:  Pred:  No: 0 done */
	
/*==============================================================/
| 78:   return null;
/==============================================================*/

	obj2 = (object_pointer) (void *) 0;
	/* goto c25_System_m2_getProperty_B3 */

	
/* c25_System_m2_getProperty_B3:  Pred:  0 No: 0 done */

	return (object_pointer)obj2;

}

