/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c25_System.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 2 c25_System_m1_nanoTime
 *
 * c7_HelloWorld_m1__init_
 * ()
 *
 * c7_HelloWorld_m2_run
 * ()
 *
 * total ()
 */

/* c25_System_m1_nanoTime #non_blocking */
/* java/lang/System.nanoTime()J */

jlong c25_System_m1_nanoTime(void)
{
	jlong l0;
	
/* c25_System_m1_nanoTime_B0:  Pred:  No: 0 done */
	
/*==============================================================/
| 103:    return 0L;
/==============================================================*/

	l0 = (0LL);
	/* goto c25_System_m1_nanoTime_B3 */

	
/* c25_System_m1_nanoTime_B3:  Pred:  0 No: 0 done */

	return l0;

}

