/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C26_MATH_H__
#define __C26_MATH_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C26_MATH_ID ((class_id_t)26)

/* object data */
typedef struct {
/* c26_Math */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c26_Math */
} c26_Math_t;
#define C26_MATH_OBJ(_obj_) ((c26_Math_t*)(_obj_))
#define KESO_ALLOC_C26_MATH() KESO_ALLOC(C26_MATH_ID,sizeof(c26_Math_t),0)
#define KESO_ALLOC_STACK_C26_MATH(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C26_MATH_ID,sizeof(c26_Math_t),0)
#define KESO_ALLOC_INLINE_C26_MATH() KESO_ALLOC(C26_MATH_ID,sizeof(c26_Math_t),0)

/* class methods prototypes */



#endif /* !defined(__C26_MATH_H__) */
