/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C27_OUTPUTSTREAM_H__
#define __C27_OUTPUTSTREAM_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C27_OUTPUTSTREAM_ID ((class_id_t)27)

/* object data */
typedef struct {
/* c27_OutputStream */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c27_OutputStream */
} c27_OutputStream_t;
#define C27_OUTPUTSTREAM_OBJ(_obj_) ((c27_OutputStream_t*)(_obj_))

/* class methods prototypes */



#endif /* !defined(__C27_OUTPUTSTREAM_H__) */
