/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C28_FILTEROUTPUTSTREAM_H__
#define __C28_FILTEROUTPUTSTREAM_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C28_FILTEROUTPUTSTREAM_ID ((class_id_t)28)

/* object data */
typedef struct {
/* c28_FilterOutputStream */
	object_pointer c28f1_out;
/* c27_OutputStream */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c27_OutputStream */
/* c28_FilterOutputStream */
} c28_FilterOutputStream_t;
#define C28_FILTEROUTPUTSTREAM_OBJ(_obj_) ((c28_FilterOutputStream_t*)((object_pointer*)(_obj_)-1))
#define ACCFIELD_C28_FILTEROUTPUTSTREAM_C28F1_OUT(_obj_) (C28_FILTEROUTPUTSTREAM_OBJ(_obj_)->c28f1_out)
#define KESO_ALLOC_C28_FILTEROUTPUTSTREAM() KESO_ALLOC(C28_FILTEROUTPUTSTREAM_ID,sizeof(c28_FilterOutputStream_t),1)
#define KESO_ALLOC_STACK_C28_FILTEROUTPUTSTREAM(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C28_FILTEROUTPUTSTREAM_ID,sizeof(c28_FilterOutputStream_t),1)
#define KESO_ALLOC_INLINE_C28_FILTEROUTPUTSTREAM() KESO_ALLOC(C28_FILTEROUTPUTSTREAM_ID,sizeof(c28_FilterOutputStream_t),1)

/* class methods prototypes */



#endif /* !defined(__C28_FILTEROUTPUTSTREAM_H__) */
