/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c30_DebugOutPrintStream.h"
#include "c32_DebugOutOutputStream.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 2 c30_DebugOutPrintStream_m3__clinit_
 *
 * <kore>
 * ()
 *
 * <kore>
 * ()
 *
 * total ()
 */

/* c30_DebugOutPrintStream_m3__clinit_ #non_blocking */
/* keso/io/DebugOutPrintStream.<clinit>()V */

void c30_DebugOutPrintStream_m3__clinit_(void)
{
	object_pointer obj0_0;
	
/* c30_DebugOutPrintStream_m3__clinit__B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 30:  private static final DebugOutOutputStream os = new DebugOutOutputStream();
/==============================================================*/

	obj0_0 = KESO_ALLOC_C32_DEBUGOUTOUTPUTSTREAM();
	/* goto c30_DebugOutPrintStream_m3__clinit__B12 */

	
/* c30_DebugOutPrintStream_m3__clinit__B12:  Pred:  0 No: 2 done */

	return;

}

