/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c30_DebugOutPrintStream.h"
#include "c8_DebugOut.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 1 c30_DebugOutPrintStream_m4_println
 *
 * c7_HelloWorld_m2_run
 * (valid java/io/PrintStream, long)
 *
 * total (valid java/io/PrintStream, long)
 */

/* c30_DebugOutPrintStream_m4_println #non_blocking */
/* keso/io/DebugOutPrintStream.println(J)V */

void c30_DebugOutPrintStream_m4_println(object_pointer obj0, jlong l1)
{
	
/* c30_DebugOutPrintStream_m4_println_B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 97:   DebugOut.println(v);
| 98:  }
/==============================================================*/

	c8_DebugOut_m5_println(l1);
	/* goto c30_DebugOutPrintStream_m4_println_B6 */

	
/* c30_DebugOutPrintStream_m4_println_B6:  Pred:  0 No: 2 done */

	return;

}

