/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C30_DEBUGOUTPRINTSTREAM_H__
#define __C30_DEBUGOUTPRINTSTREAM_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C30_DEBUGOUTPRINTSTREAM_ID ((class_id_t)30)

/* object data */
typedef struct {
/* c30_DebugOutPrintStream */
/* c29_PrintStream */
/* c28_FilterOutputStream */
	object_pointer c28f1_out;
/* c27_OutputStream */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c27_OutputStream */
/* c28_FilterOutputStream */
	jbyte c29f2_error;
/* c29_PrintStream */
/* c30_DebugOutPrintStream */
} c30_DebugOutPrintStream_t;
#define C30_DEBUGOUTPRINTSTREAM_OBJ(_obj_) ((c30_DebugOutPrintStream_t*)((object_pointer*)(_obj_)-1))
#define ACCFIELD_C30_DEBUGOUTPRINTSTREAM_C29F2_ERROR(_obj_) (C30_DEBUGOUTPRINTSTREAM_OBJ(_obj_)->c29f2_error)
#define ACCFIELD_C30_DEBUGOUTPRINTSTREAM_C28F1_OUT(_obj_) (C30_DEBUGOUTPRINTSTREAM_OBJ(_obj_)->c28f1_out)
#define KESO_ALLOC_C30_DEBUGOUTPRINTSTREAM() KESO_ALLOC(C30_DEBUGOUTPRINTSTREAM_ID,sizeof(c30_DebugOutPrintStream_t),1)
#define KESO_ALLOC_STACK_C30_DEBUGOUTPRINTSTREAM(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C30_DEBUGOUTPRINTSTREAM_ID,sizeof(c30_DebugOutPrintStream_t),1)
#define KESO_ALLOC_INLINE_C30_DEBUGOUTPRINTSTREAM() KESO_ALLOC(C30_DEBUGOUTPRINTSTREAM_ID,sizeof(c30_DebugOutPrintStream_t),1)

/* class methods prototypes */
/* c30_DebugOutPrintStream_m3__clinit_ #non_blocking */
/* <clinit>()V */
void c30_DebugOutPrintStream_m3__clinit_(void);
#include "c29_PrintStream.h"
/* import INVOKE_C29_PRINTSTREAM_M4_PRINTLN */
#define INVOKE_C30_DEBUGOUTPRINTSTREAM_M4_PRINTLN INVOKE_C29_PRINTSTREAM_M4_PRINTLN
/* c30_DebugOutPrintStream_m4_println #non_blocking */
/* println(J)V */
void c30_DebugOutPrintStream_m4_println(object_pointer obj0, jlong l1);
#include "c29_PrintStream.h"
/* import INVOKE_C29_PRINTSTREAM_M2_PRINTLN */
#define INVOKE_C30_DEBUGOUTPRINTSTREAM_M6_PRINTLN INVOKE_C29_PRINTSTREAM_M2_PRINTLN
/* c30_DebugOutPrintStream_m6_println #non_blocking */
/* println(Ljava/lang/String;)V */
void c30_DebugOutPrintStream_m6_println(object_pointer obj0, object_pointer obj1);
#include "c29_PrintStream.h"
/* import INVOKE_C29_PRINTSTREAM_M3_PRINT */
#define INVOKE_C30_DEBUGOUTPRINTSTREAM_M7_PRINT INVOKE_C29_PRINTSTREAM_M3_PRINT
/* c30_DebugOutPrintStream_m7_print #non_blocking */
/* print(Ljava/lang/String;)V */
void c30_DebugOutPrintStream_m7_print(object_pointer obj0, object_pointer obj1);
#include "c29_PrintStream.h"
/* import INVOKE_C29_PRINTSTREAM_M5_PRINTLN */
#define INVOKE_C30_DEBUGOUTPRINTSTREAM_M8_PRINTLN INVOKE_C29_PRINTSTREAM_M5_PRINTLN
/* c30_DebugOutPrintStream_m8_println #non_blocking */
/* println(I)V */
void c30_DebugOutPrintStream_m8_println(object_pointer obj0, jint i1);



#endif /* !defined(__C30_DEBUGOUTPRINTSTREAM_H__) */
