/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c15_StringBuilder.h"
#include "c30_DebugOutPrintStream.h"
#include "c8_DebugOut.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 2 c30_DebugOutPrintStream_m7_print
 *
 * c7_HelloWorld_m2_run
 * (valid java/io/PrintStream, "hash value: " java/lang/String)
 *
 * c7_HelloWorld_m2_run
 * (valid java/io/PrintStream, "	hash value again: " java/lang/String)
 *
 * total (valid java/io/PrintStream, valid java/lang/String)
 */

/* c30_DebugOutPrintStream_m7_print #non_blocking */
/* keso/io/DebugOutPrintStream.print(Ljava/lang/String;)V */

void c30_DebugOutPrintStream_m7_print(object_pointer obj0, object_pointer obj1)
{
	object_pointer obj2;
	
/* c30_DebugOutPrintStream_m7_print_B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 41:   DebugOut.print(s);
| 42:  }
/==============================================================*/

	obj2 = SC8_DEBUGOUT_C8F1_BUF(((domain_t *) &__DOSEK_APPDATA_dom1__DDesc));
	c15_StringBuilder_m1_append(obj2, obj1);
	/* goto c30_DebugOutPrintStream_m7_print_B6 */

	
/* c30_DebugOutPrintStream_m7_print_B6:  Pred:  0 No: 3 done */

	return;

}

