/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C31_NULLPRINTSTREAM_H__
#define __C31_NULLPRINTSTREAM_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C31_NULLPRINTSTREAM_ID ((class_id_t)31)

/* object data */
typedef struct {
/* c31_NullPrintStream */
/* c29_PrintStream */
/* c28_FilterOutputStream */
	object_pointer c28f1_out;
/* c27_OutputStream */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c27_OutputStream */
/* c28_FilterOutputStream */
	jbyte c29f2_error;
/* c29_PrintStream */
/* c31_NullPrintStream */
} c31_NullPrintStream_t;
#define C31_NULLPRINTSTREAM_OBJ(_obj_) ((c31_NullPrintStream_t*)((object_pointer*)(_obj_)-1))
#define ACCFIELD_C31_NULLPRINTSTREAM_C29F2_ERROR(_obj_) (C31_NULLPRINTSTREAM_OBJ(_obj_)->c29f2_error)
#define ACCFIELD_C31_NULLPRINTSTREAM_C28F1_OUT(_obj_) (C31_NULLPRINTSTREAM_OBJ(_obj_)->c28f1_out)
#define KESO_ALLOC_C31_NULLPRINTSTREAM() KESO_ALLOC(C31_NULLPRINTSTREAM_ID,sizeof(c31_NullPrintStream_t),1)
#define KESO_ALLOC_STACK_C31_NULLPRINTSTREAM(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C31_NULLPRINTSTREAM_ID,sizeof(c31_NullPrintStream_t),1)
#define KESO_ALLOC_INLINE_C31_NULLPRINTSTREAM() KESO_ALLOC(C31_NULLPRINTSTREAM_ID,sizeof(c31_NullPrintStream_t),1)

/* class methods prototypes */



#endif /* !defined(__C31_NULLPRINTSTREAM_H__) */
