/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C32_DEBUGOUTOUTPUTSTREAM_H__
#define __C32_DEBUGOUTOUTPUTSTREAM_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C32_DEBUGOUTOUTPUTSTREAM_ID ((class_id_t)32)

/* object data */
typedef struct {
/* c32_DebugOutOutputStream */
/* c27_OutputStream */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c27_OutputStream */
/* c32_DebugOutOutputStream */
} c32_DebugOutOutputStream_t;
#define C32_DEBUGOUTOUTPUTSTREAM_OBJ(_obj_) ((c32_DebugOutOutputStream_t*)(_obj_))
#define KESO_ALLOC_C32_DEBUGOUTOUTPUTSTREAM() KESO_ALLOC(C32_DEBUGOUTOUTPUTSTREAM_ID,sizeof(c32_DebugOutOutputStream_t),0)
#define KESO_ALLOC_STACK_C32_DEBUGOUTOUTPUTSTREAM(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C32_DEBUGOUTOUTPUTSTREAM_ID,sizeof(c32_DebugOutOutputStream_t),0)
#define KESO_ALLOC_INLINE_C32_DEBUGOUTOUTPUTSTREAM() KESO_ALLOC(C32_DEBUGOUTOUTPUTSTREAM_ID,sizeof(c32_DebugOutOutputStream_t),0)

/* class methods prototypes */



#endif /* !defined(__C32_DEBUGOUTOUTPUTSTREAM_H__) */
