/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C4_INPUTSTREAM_H__
#define __C4_INPUTSTREAM_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C4_INPUTSTREAM_ID ((class_id_t)4)

/* object data */
typedef struct {
/* c4_InputStream */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c4_InputStream */
} c4_InputStream_t;
#define C4_INPUTSTREAM_OBJ(_obj_) ((c4_InputStream_t*)(_obj_))

/* class methods prototypes */



#endif /* !defined(__C4_INPUTSTREAM_H__) */
