/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c17_B.h"
#include "c25_System.h"
#include "c30_DebugOutPrintStream.h"
#include "c7_HelloWorld.h"
#include "keso_time.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 2 c7_HelloWorld_m1__init_
 *
 * <kore>
 * ()
 *
 * <kore>
 * ()
 *
 * total ()
 */

/* c7_HelloWorld_m1__init_ #non_blocking */
/* test/HelloWorld.<init>()V */

void c7_HelloWorld_m1__init_(object_pointer obj0)
{
	object_pointer obj1_0;
	jlong l2_0;
	object_pointer obj3_0;
	
/* c7_HelloWorld_m1__init__B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 35:  private B aobj = new B();
/==============================================================*/

	obj1_0 = KESO_ALLOC_C17_B();
	(ACCFIELD_C7_HELLOWORLD_C7F3_AOBJ(obj0)) = (object_pointer)obj1_0;
	l2_0 = keso_nanotime();
	(ACCFIELD_C7_HELLOWORLD_C7F1_START(obj0)) = (jlong)l2_0;
	obj3_0 = SC25_SYSTEM_C25F2_OUT(((domain_t *) &__DOSEK_APPDATA_dom1__DDesc));
	c30_DebugOutPrintStream_m6_println(obj3_0, ((object_pointer) ((object_pointer*) &str2+1)));
	/* goto c7_HelloWorld_m1__init__B32 */

	
/* c7_HelloWorld_m1__init__B32:  Pred:  0 No: 4 done */

	return;

}

