/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c15_StringBuilder.h"
#include "c8_DebugOut.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 3 c8_DebugOut_m6_println
 *
 * c8_DebugOut_m5_println
 * (?null java/lang/String)
 *
 * c30_DebugOutPrintStream_m6_println
 * (?null java/lang/Object)
 *
 * c30_DebugOutPrintStream_m8_println
 * (?null java/lang/String)
 *
 * total (?null java/lang/Object)
 */

/* c8_DebugOut_m6_println #non_blocking */
/* keso/io/DebugOut.println(Ljava/lang/String;)V */

void c8_DebugOut_m6_println(object_pointer obj0)
{
	object_pointer obj1_0;
	
/* c8_DebugOut_m6_println_B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 91:   buf.append(msg);
| 92:   println();
| 93:  }
/==============================================================*/

	obj1_0 = SC8_DEBUGOUT_C8F1_BUF(((domain_t *) &__DOSEK_APPDATA_dom1__DDesc));
	c15_StringBuilder_m1_append(obj1_0, obj0);
	c8_DebugOut_m2_println();
	/* goto c8_DebugOut_m6_println_B13 */

	
/* c8_DebugOut_m6_println_B13:  Pred:  0 No: 3 done */

	return;

}

