/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C8_DEBUGOUT_H__
#define __C8_DEBUGOUT_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C8_DEBUGOUT_ID ((class_id_t)8)

/* object data */
typedef struct {
/* c8_DebugOut */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c8_DebugOut */
} c8_DebugOut_t;
#define C8_DEBUGOUT_OBJ(_obj_) ((c8_DebugOut_t*)(_obj_))
#define KESO_ALLOC_C8_DEBUGOUT() KESO_ALLOC(C8_DEBUGOUT_ID,sizeof(c8_DebugOut_t),0)
#define KESO_ALLOC_STACK_C8_DEBUGOUT(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C8_DEBUGOUT_ID,sizeof(c8_DebugOut_t),0)
#define KESO_ALLOC_INLINE_C8_DEBUGOUT() KESO_ALLOC(C8_DEBUGOUT_ID,sizeof(c8_DebugOut_t),0)

/* class methods prototypes */
/* c8_DebugOut_m2_println #non_blocking */
/* println()V */
void c8_DebugOut_m2_println(void);
/* c8_DebugOut_m4__clinit_ #non_blocking */
/* <clinit>()V */
void c8_DebugOut_m4__clinit_(void);
/* c8_DebugOut_m5_println #non_blocking */
/* println(J)V */
void c8_DebugOut_m5_println(jlong l0);
/* c8_DebugOut_m6_println #non_blocking */
/* println(Ljava/lang/String;)V */
void c8_DebugOut_m6_println(object_pointer obj0);
/* c8_DebugOut_m3_raw_print #non_blocking */
/* raw_print(Ljava/lang/StringBuilder;)V */
void c8_DebugOut_m3_raw_print(object_pointer obj0);



#endif /* !defined(__C8_DEBUGOUT_H__) */
