/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c19_Long.h"
#include "c8_DebugOut.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 1 c8_DebugOut_m5_println
 *
 * c30_DebugOutPrintStream_m4_println
 * (long)
 *
 * total (long)
 */

/* c8_DebugOut_m5_println #non_blocking */
/* keso/io/DebugOut.println(J)V */

void c8_DebugOut_m5_println(jlong l0)
{
	object_pointer obj2_0;
	
/* c8_DebugOut_m5_println_B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 78:   println(Long.toString(value));
| 79:  }
/==============================================================*/

	obj2_0 = c19_Long_m1_toString(l0);
	c8_DebugOut_m6_println(obj2_0);
	/* goto c8_DebugOut_m5_println_B9 */

	
/* c8_DebugOut_m5_println_B9:  Pred:  0 No: 2 done */

	return;

}

