/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c15_StringBuilder.h"
#include "c8_DebugOut.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 2 c8_DebugOut_m4__clinit_
 *
 * <kore>
 * ()
 *
 * <kore>
 * ()
 *
 * total ()
 */

/* c8_DebugOut_m4__clinit_ #non_blocking */
/* keso/io/DebugOut.<clinit>()V */

void c8_DebugOut_m4__clinit_(void)
{
	object_pointer obj0_0;
	
/* c8_DebugOut_m4__clinit__B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 31:  private final static StringBuilder buf = new StringBuilder();
/==============================================================*/

	obj0_0 = KESO_ALLOC_C15_STRINGBUILDER();
	c15_StringBuilder_m3__init_(obj0_0);
	SC8_DEBUGOUT_C8F1_BUF(((domain_t *) &__DOSEK_APPDATA_dom1__DDesc)) = (object_pointer)obj0_0;
	/* goto c8_DebugOut_m4__clinit__B12 */

	
/* c8_DebugOut_m4__clinit__B12:  Pred:  0 No: 3 done */

	return;

}

