/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c15_StringBuilder.h"
#include "c8_DebugOut.h"
#include "char_array.h"
#include "keso_exceptions.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 1 c8_DebugOut_m2_println
 *
 * c8_DebugOut_m6_println
 * ()
 *
 * total ()
 */

/* c8_DebugOut_m2_println #non_blocking */
/* keso/io/DebugOut.println()V */

void c8_DebugOut_m2_println(void)
{
	object_pointer obj0_0;
	object_pointer obj3;
	jint i4;
	object_pointer obj6;
	
/* c8_DebugOut_m2_println_B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 111:   StringBuilder b = buf;
| 112:   b.append("\r\n");
| 113:   raw_print(b);
| 114:   b.setLength(0);
/==============================================================*/

	obj0_0 = SC8_DEBUGOUT_C8F1_BUF(((domain_t *) &__DOSEK_APPDATA_dom1__DDesc));
	c15_StringBuilder_m1_append(obj0_0, ((object_pointer) ((object_pointer*) &str0+1)));
	c8_DebugOut_m3_raw_print(obj0_0);
	c15_StringBuilder_m7_ensureCapacity(obj0_0, (0));
	if ((0)<=(ACCFIELD_C15_STRINGBUILDER_C15F2_LENGTH(obj0_0))) goto z16_c15_StringBuilder_m2_setLength_B45;

	
/* z13_c15_StringBuilder_m2_setLength_B17:  Pred:  0 No: 4 done */

	i4 = (ACCFIELD_C15_STRINGBUILDER_C15F2_LENGTH(obj0_0));

	
z3_c15_StringBuilder_m2_setLength_B18: /* Pred:  13 29 No: 5 done */

	if (i4>=(0)) goto z18_c15_StringBuilder_m2_setLength_B48;

	
/* z14_c15_StringBuilder_m2_setLength_B29:  Pred:  18 No: 7 done */

	obj3 = (ACCFIELD_C15_STRINGBUILDER_C15F1_DATA(obj0_0));
				KESO_CHECK_CASTORE_NULLPOINTER(obj3,"c8_DebugOut_m2_println",17, 1);

	
/* z15_c15_StringBuilder_m2_setLength_B29:  Pred:  23 No: 8 done */

				KESO_CHECK_CASTORE_ARRAY_NOTNULL(obj3,i4,"c8_DebugOut_m2_println",17, 2);
	CHAR_ARRAY_LEA(obj3, i4) = (0);
	i4 = (i4+0x1);
	goto z3_c15_StringBuilder_m2_setLength_B18;

	
z16_c15_StringBuilder_m2_setLength_B45: /* Pred:  0 No: 14 done */

	obj6 = (ACCFIELD_C15_STRINGBUILDER_C15F1_DATA(obj0_0));
				KESO_CHECK_CASTORE_NULLPOINTER(obj6,"c8_DebugOut_m2_println",17, 3);

	
/* z17_c15_StringBuilder_m2_setLength_B45:  Pred:  39 No: 15 done */

				KESO_CHECK_CASTORE_ARRAY_NOTNULL(obj6,0,"c8_DebugOut_m2_println",17, 4);
	CHAR_ARRAY_LEA(obj6, (0)) = (0);

	
z18_c15_StringBuilder_m2_setLength_B48: /* Pred:  45 18 No: 11 done */
	
/*==============================================================/
| 115:  }
/==============================================================*/

	(ACCFIELD_C15_STRINGBUILDER_C15F2_LENGTH(obj0_0)) = (jint)(0);
	/* goto c8_DebugOut_m2_println_B22 */

	
/* c8_DebugOut_m2_println_B22:  Pred:  46 No: 12 done */

	return;

}

