/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c9_TaskService.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 1 c9_TaskService_m2_terminate
 *
 * c7_HelloWorld_m2_run
 * ()
 *
 * total ()
 */

/* c9_TaskService_m2_terminate #non_blocking */
/* keso/core/TaskService.terminate()I */

jint c9_TaskService_m2_terminate(void)
{
	jint i0;
	
/* c9_TaskService_m2_terminate_B0:  Pred:  No: 0 done */
	
/*==============================================================/
| 64:  public static int terminate() { return E_OK; }
/==============================================================*/

	i0 = (0);
	/* goto c9_TaskService_m2_terminate_B3 */

	
/* c9_TaskService_m2_terminate_B3:  Pred:  0 No: 0 done */

	return i0;

}

