/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "rds.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/* heap for domain dom1, size is 3145728 */
char __DOSEK_APPDATA_dom1__heap[3145728] ALIGN4;
struct domain_rds_t __DOSEK_APPDATA_dom1__DDesc = {
	/* init base fields */
	{ /* static refs */ NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, },
	3145728 /* heap_size */,
	3145728 /* heap_free */,
	{ /* init heap (type rds) */
		__DOSEK_APPDATA_dom1__heap+3145728 /* heap_end */,
		__DOSEK_APPDATA_dom1__heap /* new_ptr */,
	},
};


