/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __DOMAINS_H__
#define __DOMAINS_H__
#include "keso_object_pointer.h"
#include "keso_static_fields.h"
#include "keso_types.h"
#include "global.h"


#define KESO_NUM_JAVADOMAINS 1
#include "rds.h"

#define DOMAIN_DESC_BASEFIELDS \
	object_pointer  static_ref[KESO_NUM_STATIC_REFS];\
	const unsigned int heap_size;\
	unsigned int heap_free;\

struct DOMAINDESC {
	DOMAIN_DESC_BASEFIELDS
} ATTR_MAYALIAS;
typedef struct DOMAINDESC domain_t;
struct domain_rds_t {
	DOMAIN_DESC_BASEFIELDS
	struct {
		KESO_CONST char* heap_end;
		char* new_ptr;
	} hd;
};
#define DOMAIN_ZERO NULL
#define KESO_CURRENT_DOMAIN (((domain_t *) &__DOSEK_APPDATA_dom1__DDesc))
#define KESO_CURRENT_DOMAIN_GET_ENC KESO_CURRENT_DOMAIN
#define KESO_CURRENT_DOMAIN_GET KESO_CURRENT_DOMAIN
#include "rds.h"

#define KESO_ALLOC(_cls_,_size_,_roff_) keso_rds_alloc(_cls_,_size_,_roff_)

#define keso_allocObject(ID) KESO_ALLOC(ID, CLS_SIZE(ID), CLS_ROFF(ID))
extern struct domain_rds_t __DOSEK_APPDATA_dom1__DDesc;
extern char __DOSEK_APPDATA_dom1__heap[3145728];



#endif /* !defined(__DOMAINS_H__) */
