/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __I34_NONCOPYABLE_H__
#define __I34_NONCOPYABLE_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define I34_NONCOPYABLE_ID ((class_id_t)34)

/* object data */
typedef struct {
/* i34_NonCopyable */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* i34_NonCopyable */
} i34_NonCopyable_t;
#define I34_NONCOPYABLE_OBJ(_obj_) ((i34_NonCopyable_t*)(_obj_))

/* class methods prototypes */



#endif /* !defined(__I34_NONCOPYABLE_H__) */
