/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "global.h"
#include "c20_Integer.h"
#include "c23_String.h"
#include "c30_DebugOutPrintStream.h"
#include "c25_System.h"
#include "c8_DebugOut.h"
#include "c19_Long.h"


#include "domains.h"
void PostTaskHook() {
	// At least an empty PostTaskHook to satisfy ProOSEK
}

void StartupHook() {
	/* Initialize keso_task_index */
	keso_task_index[helloworldTask] = &__DOSEK_APPDATA_dom1__helloworldTask_obj;
	// Initialize heaps

	/* Call class constructors */
	{
		/* Domain: dom1 */
		c8_DebugOut_m4__clinit_();
		c30_DebugOutPrintStream_m3__clinit_();
		c25_System_m3__clinit_();
	}

	/* Call each Task's constructor */
	c7_HelloWorld_m1__init_(((object_pointer) ((object_pointer*) &__DOSEK_APPDATA_dom1__helloworldTask_user_obj+1)));

}

void PreTaskHook() {
	// Initialize keso_curr_task and keso_curr_domain (if multi domain)
	KESO_TASKCLASSTYPE *ct = keso_curr_task_fkt();
	keso_curr_task = ct;
}

TASK (helloworldTask) {
	c7_HelloWorld_m2_run(((object_pointer) ((object_pointer*) &__DOSEK_APPDATA_dom1__helloworldTask_user_obj+1)));
	TerminateTask();
}

