/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __RDS_H__
#define __RDS_H__
#include "keso_object_pointer.h"
#include "keso_types.h"
object_pointer keso_rds_alloc(class_id_t class_id, obj_size_t size, obj_size_t roff);




#endif /* !defined(__RDS_H__) */
