/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C10_NUMBER_H__
#define __C10_NUMBER_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C10_NUMBER_ID ((class_id_t)10)

/* object data */
typedef struct {
/* c10_Number */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c10_Number */
} c10_Number_t;
#define C10_NUMBER_OBJ(_obj_) ((c10_Number_t*)(_obj_))

/* class methods prototypes */



#endif /* !defined(__C10_NUMBER_H__) */
