/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c11_Integer.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 1 c11_Integer_m2__clinit_
 *
 * <kore>
 * ()
 *
 * total ()
 */

/* c11_Integer_m2__clinit_ #non_blocking */
/* java/lang/Integer.<clinit>()V */

void c11_Integer_m2__clinit_(void)
{
	
/* c11_Integer_m2__clinit__B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 28:  public static final Class TYPE = Class.getPrimitiveClass("int");
/==============================================================*/

	/* goto c11_Integer_m2__clinit__B10 */

	
/* c11_Integer_m2__clinit__B10:  Pred:  0 No: 2 done */

	return;

}

