/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c11_Integer.h"
#include "c8_StringBuilder.h"
#include "char_array.h"
#include "keso_exceptions.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 2 c11_Integer_m1_toString
 *
 * c7_DebugOut_m7_println
 * (int)
 *
 * c8_StringBuilder_m8_append
 * (int)
 *
 * total (int)
 */

/* c11_Integer_m1_toString #non_blocking */
/* java/lang/Integer.toString(I)Ljava/lang/String; */

object_pointer c11_Integer_m1_toString(jint i0)
{
	jint i13;
	jint i15;
	jint i20;
	jint i23;
	jint i24;
	object_pointer obj25;
	jint i26;
	jint i29;
	object_pointer obj35;
	object_pointer obj36;
	object_pointer obj39;
	
/* c11_Integer_m1_toString_B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 113:   return toString(i, 10);
/==============================================================*/

	obj36 = KESO_ALLOC_C8_STRINGBUILDER();
	obj39 = keso_alloc_char_array(0xa);
	(ACCFIELD_C8_STRINGBUILDER_C8F1_DATA(obj36)) = (object_pointer)obj39;
	(ACCFIELD_C8_STRINGBUILDER_C8F2_LENGTH(obj36)) = (jint)(0);
	if (i0!=(0)) goto z26_c11_Integer_m3_toString_B28;

	
/* z53_c11_Integer_m3_toString_B19:  Pred:  0 No: 5 done */

	c8_StringBuilder_m10_append(obj36, 0x30);
	obj35 = c8_StringBuilder_m9_toString(obj36);
	goto c11_Integer_m1_toString_B8;

	
z26_c11_Integer_m3_toString_B28: /* Pred:  0 No: 8 done */

	i20 = (0);
	if (i0>=(0)) goto z25_c11_Integer_m3_toString_B37;

	
/* z27_c11_Integer_m3_toString_B32:  Pred:  28 No: 9 done */

	i0 = (i0* -1);
	i20 = 0x1;

	
z25_c11_Integer_m3_toString_B37: /* Pred:  28 46 32 No: 10 done */

	if (i0<=(0)) goto z24_c11_Integer_m3_toString_B60;

	
/* z30_c11_Integer_m3_toString_B41:  Pred:  37 No: 11 done */

	i13 = (i0%0xa);
	if (i13<(0)) goto z34_c13_Character_m1_forDigit_B22;

	
/* z33_c13_Character_m1_forDigit_B17:  Pred:  41 No: 17 done */

	if (i13<0xa) goto z35_c13_Character_m1_forDigit_B24;

	
z34_c13_Character_m1_forDigit_B22: /* Pred:  41 17 No: 18 done */

	i15 = (0);
	goto z54_c13_Character_m1_forDigit_B49;

	
z35_c13_Character_m1_forDigit_B24: /* Pred:  17 No: 19 done */

	if (i13>=0xa) goto z37_c13_Character_m1_forDigit_B36;

	
/* z36_c13_Character_m1_forDigit_B30:  Pred:  24 No: 20 done */

	i15 = ((jchar)(i13+0x30));
	goto z54_c13_Character_m1_forDigit_B49;

	
z37_c13_Character_m1_forDigit_B36: /* Pred:  24 No: 21 done */

	i15 = ((jchar)((i13+0x61)-0xa));
	/* goto z54_c13_Character_m1_forDigit_B49 */

	
z54_c13_Character_m1_forDigit_B49: /* Pred:  22 36 30 No: 15 done */

	c8_StringBuilder_m10_append(obj36, i15);
	i0 = (i0/0xa);
	goto z25_c11_Integer_m3_toString_B37;

	
z24_c11_Integer_m3_toString_B60: /* Pred:  37 No: 22 done */

	if (i20==(0)) goto z23_c11_Integer_m3_toString_B71;

	
/* z55_c11_Integer_m3_toString_B67:  Pred:  60 No: 24 done */

	c8_StringBuilder_m10_append(obj36, 0x2d);

	
z23_c11_Integer_m3_toString_B71: /* Pred:  60 64 No: 25 done */

	i23 = (0);

	
z56_c8_StringBuilder_m4_reverse_B9: /* Pred:  71 20 No: 27 done */

	if (i23>=((ACCFIELD_C8_STRINGBUILDER_C8F2_LENGTH(obj36))/0x2)) goto z59_c8_StringBuilder_m4_reverse_B80;

	
/* z57_c8_StringBuilder_m4_reverse_B20:  Pred:  2 No: 29 done */

	i24 = (((ACCFIELD_C8_STRINGBUILDER_C8F2_LENGTH(obj36))-0x1)-i23);
	obj25 = (ACCFIELD_C8_STRINGBUILDER_C8F1_DATA(obj36));
				KESO_CHECK_CALOAD_NULLPOINTER(obj25,"c11_Integer_m1_toString",3, 14);

	
/* z58_c8_StringBuilder_m4_reverse_B27:  Pred:  12 No: 30 done */

				KESO_CHECK_CALOAD_ARRAY_NOTNULL(obj25,i23,"c11_Integer_m1_toString",3, 15);
	i26 = CHAR_ARRAY_ALOAD(obj25, i23);
				KESO_CHECK_CALOAD_ARRAY_NOTNULL(obj25,i24,"c11_Integer_m1_toString",3, 16);
	i29 = CHAR_ARRAY_ALOAD(obj25, i24);
				KESO_CHECK_CASTORE_ARRAY_NOTNULL(obj25,i23,"c11_Integer_m1_toString",3, 17);
	CHAR_ARRAY_LEA(obj25, i23) = i29;
				KESO_CHECK_CASTORE_ARRAY_NOTNULL(obj25,i24,"c11_Integer_m1_toString",3, 18);
	CHAR_ARRAY_LEA(obj25, i24) = i26;
	i23 = (i23+0x1);
	goto z56_c8_StringBuilder_m4_reverse_B9;

	
z59_c8_StringBuilder_m4_reverse_B80: /* Pred:  2 No: 32 done */

	obj35 = c8_StringBuilder_m9_toString(obj36);
	/* goto c11_Integer_m1_toString_B8 */

	
c11_Integer_m1_toString_B8: /* Pred:  53 16 No: 7 done */

	return (object_pointer)obj35;

}

