/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C12_OSSERVICE_H__
#define __C12_OSSERVICE_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C12_OSSERVICE_ID ((class_id_t)12)

/* object data */
typedef struct {
/* c12_OSService */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c12_OSService */
} c12_OSService_t;
#define C12_OSSERVICE_OBJ(_obj_) ((c12_OSService_t*)(_obj_))
#define KESO_ALLOC_C12_OSSERVICE() KESO_ALLOC(C12_OSSERVICE_ID,sizeof(c12_OSService_t),0)
#define KESO_ALLOC_STACK_C12_OSSERVICE(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C12_OSSERVICE_ID,sizeof(c12_OSService_t),0)
#define KESO_ALLOC_INLINE_C12_OSSERVICE() KESO_ALLOC(C12_OSSERVICE_ID,sizeof(c12_OSService_t),0)

/* class methods prototypes */
/* c12_OSService_m2_shutdownOS #non_blocking */
/* shutdownOS(I)V */
void c12_OSService_m2_shutdownOS(jint i0);



#endif /* !defined(__C12_OSSERVICE_H__) */
