/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c12_OSService.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 1 c12_OSService_m2_shutdownOS
 *
 * c5_HelloWorld_m3_run
 * (0)
 *
 * total (0)
 */

/* c12_OSService_m2_shutdownOS #non_blocking */
/* keso/core/OSService.shutdownOS(I)V */

void c12_OSService_m2_shutdownOS(jint i0)
{
	
/* c12_OSService_m2_shutdownOS_B0:  Pred:  No: 0 done */
	
/*==============================================================/
| 47:  public static void shutdownOS(int error) {}
/==============================================================*/

	/* goto c12_OSService_m2_shutdownOS_B2 */

	
/* c12_OSService_m2_shutdownOS_B2:  Pred:  0 No: 0 done */

	return;

}

