/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C13_CHARACTER_H__
#define __C13_CHARACTER_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C13_CHARACTER_ID ((class_id_t)13)

/* object data */
typedef struct {
/* c13_Character */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c13_Character */
} c13_Character_t;
#define C13_CHARACTER_OBJ(_obj_) ((c13_Character_t*)(_obj_))
#define KESO_ALLOC_C13_CHARACTER() KESO_ALLOC(C13_CHARACTER_ID,sizeof(c13_Character_t),0)
#define KESO_ALLOC_STACK_C13_CHARACTER(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C13_CHARACTER_ID,sizeof(c13_Character_t),0)
#define KESO_ALLOC_INLINE_C13_CHARACTER() KESO_ALLOC(C13_CHARACTER_ID,sizeof(c13_Character_t),0)

/* class methods prototypes */



#endif /* !defined(__C13_CHARACTER_H__) */
