/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C14_EVENTS_H__
#define __C14_EVENTS_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C14_EVENTS_ID ((class_id_t)14)

/* object data */
typedef struct {
/* c14_Events */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c14_Events */
} c14_Events_t;
#define C14_EVENTS_OBJ(_obj_) ((c14_Events_t*)(_obj_))
#define KESO_ALLOC_C14_EVENTS() KESO_ALLOC(C14_EVENTS_ID,sizeof(c14_Events_t),0)
#define KESO_ALLOC_STACK_C14_EVENTS(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C14_EVENTS_ID,sizeof(c14_Events_t),0)
#define KESO_ALLOC_INLINE_C14_EVENTS() KESO_ALLOC(C14_EVENTS_ID,sizeof(c14_Events_t),0)

/* class methods prototypes */



#endif /* !defined(__C14_EVENTS_H__) */
