/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C15_MATH_H__
#define __C15_MATH_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C15_MATH_ID ((class_id_t)15)

/* object data */
typedef struct {
/* c15_Math */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c15_Math */
} c15_Math_t;
#define C15_MATH_OBJ(_obj_) ((c15_Math_t*)(_obj_))
#define KESO_ALLOC_C15_MATH() KESO_ALLOC(C15_MATH_ID,sizeof(c15_Math_t),0)
#define KESO_ALLOC_STACK_C15_MATH(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C15_MATH_ID,sizeof(c15_Math_t),0)
#define KESO_ALLOC_INLINE_C15_MATH() KESO_ALLOC(C15_MATH_ID,sizeof(c15_Math_t),0)

/* class methods prototypes */



#endif /* !defined(__C15_MATH_H__) */
