/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C17_OUTPUTSTREAM_H__
#define __C17_OUTPUTSTREAM_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C17_OUTPUTSTREAM_ID ((class_id_t)17)

/* object data */
typedef struct {
/* c17_OutputStream */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c17_OutputStream */
} c17_OutputStream_t;
#define C17_OUTPUTSTREAM_OBJ(_obj_) ((c17_OutputStream_t*)(_obj_))

/* class methods prototypes */



#endif /* !defined(__C17_OUTPUTSTREAM_H__) */
