/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C18_FILTEROUTPUTSTREAM_H__
#define __C18_FILTEROUTPUTSTREAM_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C18_FILTEROUTPUTSTREAM_ID ((class_id_t)18)

/* object data */
typedef struct {
/* c18_FilterOutputStream */
/* c17_OutputStream */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c17_OutputStream */
/* c18_FilterOutputStream */
} c18_FilterOutputStream_t;
#define C18_FILTEROUTPUTSTREAM_OBJ(_obj_) ((c18_FilterOutputStream_t*)(_obj_))
#define KESO_ALLOC_C18_FILTEROUTPUTSTREAM() KESO_ALLOC(C18_FILTEROUTPUTSTREAM_ID,sizeof(c18_FilterOutputStream_t),0)
#define KESO_ALLOC_STACK_C18_FILTEROUTPUTSTREAM(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C18_FILTEROUTPUTSTREAM_ID,sizeof(c18_FilterOutputStream_t),0)
#define KESO_ALLOC_INLINE_C18_FILTEROUTPUTSTREAM() KESO_ALLOC(C18_FILTEROUTPUTSTREAM_ID,sizeof(c18_FilterOutputStream_t),0)

/* class methods prototypes */



#endif /* !defined(__C18_FILTEROUTPUTSTREAM_H__) */
