/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C19_PRINTSTREAM_H__
#define __C19_PRINTSTREAM_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C19_PRINTSTREAM_ID ((class_id_t)19)

/* object data */
typedef struct {
/* c19_PrintStream */
/* c18_FilterOutputStream */
/* c17_OutputStream */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c17_OutputStream */
/* c18_FilterOutputStream */
/* c19_PrintStream */
} c19_PrintStream_t;
#define C19_PRINTSTREAM_OBJ(_obj_) ((c19_PrintStream_t*)(_obj_))
#define KESO_ALLOC_C19_PRINTSTREAM() KESO_ALLOC(C19_PRINTSTREAM_ID,sizeof(c19_PrintStream_t),0)
#define KESO_ALLOC_STACK_C19_PRINTSTREAM(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C19_PRINTSTREAM_ID,sizeof(c19_PrintStream_t),0)
#define KESO_ALLOC_INLINE_C19_PRINTSTREAM() KESO_ALLOC(C19_PRINTSTREAM_ID,sizeof(c19_PrintStream_t),0)

/* class methods prototypes */



#endif /* !defined(__C19_PRINTSTREAM_H__) */
