/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C20_DEBUGOUTPRINTSTREAM_H__
#define __C20_DEBUGOUTPRINTSTREAM_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C20_DEBUGOUTPRINTSTREAM_ID ((class_id_t)20)

/* object data */
typedef struct {
/* c20_DebugOutPrintStream */
/* c19_PrintStream */
/* c18_FilterOutputStream */
/* c17_OutputStream */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c17_OutputStream */
/* c18_FilterOutputStream */
/* c19_PrintStream */
/* c20_DebugOutPrintStream */
} c20_DebugOutPrintStream_t;
#define C20_DEBUGOUTPRINTSTREAM_OBJ(_obj_) ((c20_DebugOutPrintStream_t*)(_obj_))
#define KESO_ALLOC_C20_DEBUGOUTPRINTSTREAM() KESO_ALLOC(C20_DEBUGOUTPRINTSTREAM_ID,sizeof(c20_DebugOutPrintStream_t),0)
#define KESO_ALLOC_STACK_C20_DEBUGOUTPRINTSTREAM(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C20_DEBUGOUTPRINTSTREAM_ID,sizeof(c20_DebugOutPrintStream_t),0)
#define KESO_ALLOC_INLINE_C20_DEBUGOUTPRINTSTREAM() KESO_ALLOC(C20_DEBUGOUTPRINTSTREAM_ID,sizeof(c20_DebugOutPrintStream_t),0)

/* class methods prototypes */



#endif /* !defined(__C20_DEBUGOUTPRINTSTREAM_H__) */
