/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C21_NULLPRINTSTREAM_H__
#define __C21_NULLPRINTSTREAM_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C21_NULLPRINTSTREAM_ID ((class_id_t)21)

/* object data */
typedef struct {
/* c21_NullPrintStream */
/* c19_PrintStream */
/* c18_FilterOutputStream */
/* c17_OutputStream */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c17_OutputStream */
/* c18_FilterOutputStream */
/* c19_PrintStream */
/* c21_NullPrintStream */
} c21_NullPrintStream_t;
#define C21_NULLPRINTSTREAM_OBJ(_obj_) ((c21_NullPrintStream_t*)(_obj_))
#define KESO_ALLOC_C21_NULLPRINTSTREAM() KESO_ALLOC(C21_NULLPRINTSTREAM_ID,sizeof(c21_NullPrintStream_t),0)
#define KESO_ALLOC_STACK_C21_NULLPRINTSTREAM(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C21_NULLPRINTSTREAM_ID,sizeof(c21_NullPrintStream_t),0)
#define KESO_ALLOC_INLINE_C21_NULLPRINTSTREAM() KESO_ALLOC(C21_NULLPRINTSTREAM_ID,sizeof(c21_NullPrintStream_t),0)

/* class methods prototypes */



#endif /* !defined(__C21_NULLPRINTSTREAM_H__) */
