/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C22_DEBUGOUTOUTPUTSTREAM_H__
#define __C22_DEBUGOUTOUTPUTSTREAM_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C22_DEBUGOUTOUTPUTSTREAM_ID ((class_id_t)22)

/* object data */
typedef struct {
/* c22_DebugOutOutputStream */
/* c17_OutputStream */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c17_OutputStream */
/* c22_DebugOutOutputStream */
} c22_DebugOutOutputStream_t;
#define C22_DEBUGOUTOUTPUTSTREAM_OBJ(_obj_) ((c22_DebugOutOutputStream_t*)(_obj_))
#define KESO_ALLOC_C22_DEBUGOUTOUTPUTSTREAM() KESO_ALLOC(C22_DEBUGOUTOUTPUTSTREAM_ID,sizeof(c22_DebugOutOutputStream_t),0)
#define KESO_ALLOC_STACK_C22_DEBUGOUTOUTPUTSTREAM(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C22_DEBUGOUTOUTPUTSTREAM_ID,sizeof(c22_DebugOutOutputStream_t),0)
#define KESO_ALLOC_INLINE_C22_DEBUGOUTOUTPUTSTREAM() KESO_ALLOC(C22_DEBUGOUTOUTPUTSTREAM_ID,sizeof(c22_DebugOutOutputStream_t),0)

/* class methods prototypes */



#endif /* !defined(__C22_DEBUGOUTOUTPUTSTREAM_H__) */
