/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C23_THROWABLE_H__
#define __C23_THROWABLE_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C23_THROWABLE_ID ((class_id_t)23)

/* object data */
typedef struct {
/* c23_Throwable */
	object_pointer c23f1_message;
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c23_Throwable */
} c23_Throwable_t;
#define C23_THROWABLE_OBJ(_obj_) ((c23_Throwable_t*)((object_pointer*)(_obj_)-1))
#define ACCFIELD_C23_THROWABLE_C23F1_MESSAGE(_obj_) (C23_THROWABLE_OBJ(_obj_)->c23f1_message)
#define KESO_ALLOC_C23_THROWABLE() KESO_ALLOC(C23_THROWABLE_ID,sizeof(c23_Throwable_t),1)
#define KESO_ALLOC_STACK_C23_THROWABLE(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C23_THROWABLE_ID,sizeof(c23_Throwable_t),1)
#define KESO_ALLOC_INLINE_C23_THROWABLE() KESO_ALLOC(C23_THROWABLE_ID,sizeof(c23_Throwable_t),1)

/* class methods prototypes */



#endif /* !defined(__C23_THROWABLE_H__) */
