/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C25_RUNTIMEEXCEPTION_H__
#define __C25_RUNTIMEEXCEPTION_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C25_RUNTIMEEXCEPTION_ID ((class_id_t)25)

/* object data */
typedef struct {
/* c25_RuntimeException */
/* c24_Exception */
/* c23_Throwable */
	object_pointer c23f1_message;
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c23_Throwable */
/* c24_Exception */
/* c25_RuntimeException */
} c25_RuntimeException_t;
#define C25_RUNTIMEEXCEPTION_OBJ(_obj_) ((c25_RuntimeException_t*)((object_pointer*)(_obj_)-1))
#define ACCFIELD_C25_RUNTIMEEXCEPTION_C23F1_MESSAGE(_obj_) (C25_RUNTIMEEXCEPTION_OBJ(_obj_)->c23f1_message)
#define KESO_ALLOC_C25_RUNTIMEEXCEPTION() KESO_ALLOC(C25_RUNTIMEEXCEPTION_ID,sizeof(c25_RuntimeException_t),1)
#define KESO_ALLOC_STACK_C25_RUNTIMEEXCEPTION(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C25_RUNTIMEEXCEPTION_ID,sizeof(c25_RuntimeException_t),1)
#define KESO_ALLOC_INLINE_C25_RUNTIMEEXCEPTION() KESO_ALLOC(C25_RUNTIMEEXCEPTION_ID,sizeof(c25_RuntimeException_t),1)

/* class methods prototypes */



#endif /* !defined(__C25_RUNTIMEEXCEPTION_H__) */
