/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C26_STRINGINDEXOUTOFBOUNDSEXCEPTION_H__
#define __C26_STRINGINDEXOUTOFBOUNDSEXCEPTION_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C26_STRINGINDEXOUTOFBOUNDSEXCEPTION_ID ((class_id_t)26)

/* object data */
typedef struct {
/* c26_StringIndexOutOfBoundsException */
/* c25_RuntimeException */
/* c24_Exception */
/* c23_Throwable */
	object_pointer c23f1_message;
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c23_Throwable */
/* c24_Exception */
/* c25_RuntimeException */
/* c26_StringIndexOutOfBoundsException */
} c26_StringIndexOutOfBoundsException_t;
#define C26_STRINGINDEXOUTOFBOUNDSEXCEPTION_OBJ(_obj_) ((c26_StringIndexOutOfBoundsException_t*)((object_pointer*)(_obj_)-1))
#define ACCFIELD_C26_STRINGINDEXOUTOFBOUNDSEXCEPTION_C23F1_MESSAGE(_obj_) (C26_STRINGINDEXOUTOFBOUNDSEXCEPTION_OBJ(_obj_)->c23f1_message)
#define KESO_ALLOC_C26_STRINGINDEXOUTOFBOUNDSEXCEPTION() KESO_ALLOC(C26_STRINGINDEXOUTOFBOUNDSEXCEPTION_ID,sizeof(c26_StringIndexOutOfBoundsException_t),1)
#define KESO_ALLOC_STACK_C26_STRINGINDEXOUTOFBOUNDSEXCEPTION(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C26_STRINGINDEXOUTOFBOUNDSEXCEPTION_ID,sizeof(c26_StringIndexOutOfBoundsException_t),1)
#define KESO_ALLOC_INLINE_C26_STRINGINDEXOUTOFBOUNDSEXCEPTION() KESO_ALLOC(C26_STRINGINDEXOUTOFBOUNDSEXCEPTION_ID,sizeof(c26_StringIndexOutOfBoundsException_t),1)

/* class methods prototypes */



#endif /* !defined(__C26_STRINGINDEXOUTOFBOUNDSEXCEPTION_H__) */
