/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C27_GC_H__
#define __C27_GC_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C27_GC_ID ((class_id_t)27)

/* object data */
typedef struct {
/* c27_GC */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c27_GC */
} c27_GC_t;
#define C27_GC_OBJ(_obj_) ((c27_GC_t*)(_obj_))
#define KESO_ALLOC_C27_GC() KESO_ALLOC(C27_GC_ID,sizeof(c27_GC_t),0)
#define KESO_ALLOC_STACK_C27_GC(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C27_GC_ID,sizeof(c27_GC_t),0)
#define KESO_ALLOC_INLINE_C27_GC() KESO_ALLOC(C27_GC_ID,sizeof(c27_GC_t),0)

/* class methods prototypes */



#endif /* !defined(__C27_GC_H__) */
