/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C28_EVENTSERVICE_H__
#define __C28_EVENTSERVICE_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C28_EVENTSERVICE_ID ((class_id_t)28)

/* object data */
typedef struct {
/* c28_EventService */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c28_EventService */
} c28_EventService_t;
#define C28_EVENTSERVICE_OBJ(_obj_) ((c28_EventService_t*)(_obj_))
#define KESO_ALLOC_C28_EVENTSERVICE() KESO_ALLOC(C28_EVENTSERVICE_ID,sizeof(c28_EventService_t),0)
#define KESO_ALLOC_STACK_C28_EVENTSERVICE(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C28_EVENTSERVICE_ID,sizeof(c28_EventService_t),0)
#define KESO_ALLOC_INLINE_C28_EVENTSERVICE() KESO_ALLOC(C28_EVENTSERVICE_ID,sizeof(c28_EventService_t),0)

/* class methods prototypes */
/* c28_EventService_m1_waitEvent #self */
/* waitEvent(I)I */
jint c28_EventService_m1_waitEvent(object_pointer* pref, jint i0);
/* c28_EventService_m2_clearEvent #non_blocking */
/* clearEvent(I)I */
jint c28_EventService_m2_clearEvent(jint i0);



#endif /* !defined(__C28_EVENTSERVICE_H__) */
