/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c28_EventService.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 1 c28_EventService_m1_waitEvent
 *
 * c5_HelloWorld_m2_printList
 * (1)
 *
 * total (1)
 */

/* c28_EventService_m1_waitEvent #self */
/* keso/core/EventService.waitEvent(I)I */

jint c28_EventService_m1_waitEvent(object_pointer* pref, jint i0)
{
	jint i1;
	
/* c28_EventService_m1_waitEvent_B0:  Pred:  No: 0 done */
	
/*==============================================================/
| 60:  public static int waitEvent(int evMask) { return 0; }
/==============================================================*/

	i1 = (0);
	/* goto c28_EventService_m1_waitEvent_B3 */

	
/* c28_EventService_m1_waitEvent_B3:  Pred:  0 No: 0 done */

	return i1;

}

