/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c28_EventService.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 1 c28_EventService_m2_clearEvent
 *
 * c5_HelloWorld_m2_printList
 * (1)
 *
 * total (1)
 */

/* c28_EventService_m2_clearEvent #non_blocking */
/* keso/core/EventService.clearEvent(I)I */

jint c28_EventService_m2_clearEvent(jint i0)
{
	jint i1;
	
/* c28_EventService_m2_clearEvent_B0:  Pred:  No: 0 done */
	
/*==============================================================/
| 42:  public static int clearEvent(int evMask) { return 0; }
/==============================================================*/

	i1 = (0);
	/* goto c28_EventService_m2_clearEvent_B3 */

	
/* c28_EventService_m2_clearEvent_B3:  Pred:  0 No: 0 done */

	return i1;

}

