/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c29_String.h"
#include "char_array.h"
#include "keso_exceptions.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 1 c29_String_m3_getChars
 *
 * c8_StringBuilder_m1_append
 * (valid java/lang/Object, 0, int, ?null [C, int)
 *
 * total (valid java/lang/Object, 0, int, ?null [C, int)
 */

/* c29_String_m3_getChars #non_blocking */
/* java/lang/String.getChars(II[CI)V */

void c29_String_m3_getChars(object_pointer obj0, jint i2, object_pointer obj3, jint i4)
{
	object_pointer obj5_0;
	object_pointer obj6_0;
	jint i12;
	jint i14;
	jint i18;
	
/* c29_String_m3_getChars_B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 142:   if ((srcBegin < 0)
/==============================================================*/

	obj5_0 = (ACCFIELD_C29_STRING_C29F1_VALUE(obj0));
				KESO_CHECK_ARRAYLENGTH_NULLPOINTER(obj5_0,"c29_String_m3_getChars",9, 19);

	
/* z17_c29_String_m3_getChars_B10:  Pred:  0 No: 4 done */

	if (i2>KESO_GET_ARRAY_LENGTH(obj5_0)) goto z19_c29_String_m3_getChars_B33;

	
/* c29_String_m3_getChars_B13:  Pred:  9 No: 5 done */

	if (i2<(0)) goto z19_c29_String_m3_getChars_B33;

	
/* z18_c29_String_m3_getChars_B26:  Pred:  13 No: 7 done */

	if (KESO_GET_ARRAY_LENGTH(obj3)>=(i2+i4)) goto z20_c29_String_m3_getChars_B45;

	
z19_c29_String_m3_getChars_B33: /* Pred:  9 13 18 No: 9 done */
	
/*==============================================================/
: 143:     || (srcEnd > value.length)
: 144:     || (srcEnd < srcBegin)
: 145:     || (dst.length < (srcEnd - srcBegin + dstBegin)))
| 146:    throw out_of_bounds();
/==============================================================*/

	/* throw obj0.out_of_bounds() */
	/* For now we just halt. */
	while (1) { __asm__ __volatile__ ("nop"); }

	
z20_c29_String_m3_getChars_B45: /* Pred:  18 No: 11 done */
	
/*==============================================================/
| 147:   charArrayCopy(value, srcBegin, dst, dstBegin, srcEnd - srcBegin);
/==============================================================*/

	obj6_0 = (ACCFIELD_C29_STRING_C29F1_VALUE(obj0));
	i12 = (0);

	
z2_c29_String_m7_charArrayCopy_B3: /* Pred:  34 10 No: 12 done */

	if (i12>=i2) goto c29_String_m3_getChars_B50;

	
/* z3_c29_String_m7_charArrayCopy_B10:  Pred:  3 No: 13 done */

	i14 = (i4+i12);
				KESO_CHECK_CALOAD_NULLPOINTER(obj6_0,"c29_String_m3_getChars",45, 20);

	
/* z21_c29_String_m7_charArrayCopy_B21:  Pred:  10 No: 14 done */

				KESO_CHECK_CALOAD_ARRAY_NOTNULL(obj6_0,i12,"c29_String_m3_getChars",45, 21);
	i18 = CHAR_ARRAY_ALOAD(obj6_0, i12);
				KESO_CHECK_CASTORE_ARRAY_NOTNULL(obj3,i14,"c29_String_m3_getChars",45, 22);
	CHAR_ARRAY_LEA(obj3, i14) = i18;
	i12 = (i12+0x1);
	goto z2_c29_String_m7_charArrayCopy_B3;

	
c29_String_m3_getChars_B50: /* Pred:  3 No: 17 done */
	
/*==============================================================/
| 148:  }
/==============================================================*/

	return;

}

