/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C29_STRING_H__
#define __C29_STRING_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C29_STRING_ID ((class_id_t)29)

/* object data */
typedef struct {
/* c29_String */
	object_pointer c29f1_value;
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c29_String */
} c29_String_t;
#define C29_STRING_OBJ(_obj_) ((c29_String_t*)((object_pointer*)(_obj_)-1))
#define ACCFIELD_C29_STRING_C29F1_VALUE(_obj_) (C29_STRING_OBJ(_obj_)->c29f1_value)
#define KESO_ALLOC_C29_STRING() KESO_ALLOC(C29_STRING_ID,sizeof(c29_String_t),1)
#define KESO_ALLOC_STACK_C29_STRING(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C29_STRING_ID,sizeof(c29_String_t),1)
#define KESO_ALLOC_INLINE_C29_STRING() KESO_ALLOC(C29_STRING_ID,sizeof(c29_String_t),1)

/* class methods prototypes */
/* c29_String_m4__clinit_ #non_blocking */
/* <clinit>()V */
void c29_String_m4__clinit_(void);
/* c29_String_m3_getChars #non_blocking */
/* getChars(II[CI)V */
void c29_String_m3_getChars(object_pointer obj0, jint i2, object_pointer obj3, jint i4);
/* c29_String_m6_out_of_bounds #non_blocking */
/* out_of_bounds()Ljava/lang/StringIndexOutOfBoundsException; */
object_pointer c29_String_m6_out_of_bounds(object_pointer obj0);



#endif /* !defined(__C29_STRING_H__) */
