/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c29_String.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 1 c29_String_m4__clinit_
 *
 * <kore>
 * ()
 *
 * total ()
 */

/* c29_String_m4__clinit_ #non_blocking */
/* java/lang/String.<clinit>()V */

void c29_String_m4__clinit_(void)
{
	
/* c29_String_m4__clinit__B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 31:  final private static char[] NULL = new char[0];
/==============================================================*/

	/* goto c29_String_m4__clinit__B8 */

	
/* c29_String_m4__clinit__B8:  Pred:  0 No: 3 done */

	return;

}

