/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C31_CONFIG_H__
#define __C31_CONFIG_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C31_CONFIG_ID ((class_id_t)31)

/* object data */
typedef struct {
/* c31_Config */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c31_Config */
} c31_Config_t;
#define C31_CONFIG_OBJ(_obj_) ((c31_Config_t*)(_obj_))
#define KESO_ALLOC_C31_CONFIG() KESO_ALLOC(C31_CONFIG_ID,sizeof(c31_Config_t),0)
#define KESO_ALLOC_STACK_C31_CONFIG(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C31_CONFIG_ID,sizeof(c31_Config_t),0)
#define KESO_ALLOC_INLINE_C31_CONFIG() KESO_ALLOC(C31_CONFIG_ID,sizeof(c31_Config_t),0)

/* class methods prototypes */



#endif /* !defined(__C31_CONFIG_H__) */
