/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C32_SYSTEM_H__
#define __C32_SYSTEM_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C32_SYSTEM_ID ((class_id_t)32)

/* object data */
typedef struct {
/* c32_System */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c32_System */
} c32_System_t;
#define C32_SYSTEM_OBJ(_obj_) ((c32_System_t*)(_obj_))
#define KESO_ALLOC_C32_SYSTEM() KESO_ALLOC(C32_SYSTEM_ID,sizeof(c32_System_t),0)
#define KESO_ALLOC_STACK_C32_SYSTEM(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C32_SYSTEM_ID,sizeof(c32_System_t),0)
#define KESO_ALLOC_INLINE_C32_SYSTEM() KESO_ALLOC(C32_SYSTEM_ID,sizeof(c32_System_t),0)

/* class methods prototypes */



#endif /* !defined(__C32_SYSTEM_H__) */
