/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C3_INPUTSTREAM_H__
#define __C3_INPUTSTREAM_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C3_INPUTSTREAM_ID ((class_id_t)3)

/* object data */
typedef struct {
/* c3_InputStream */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c3_InputStream */
} c3_InputStream_t;
#define C3_INPUTSTREAM_OBJ(_obj_) ((c3_InputStream_t*)(_obj_))

/* class methods prototypes */



#endif /* !defined(__C3_INPUTSTREAM_H__) */
