/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C4_ALARM_H__
#define __C4_ALARM_H__
#include "keso_object_pointer.h"
#include "keso_os.h"
#include "keso_types.h"

#define C4_ALARM_ID ((class_id_t)4)

/* object data */
typedef struct {
/* c4_Alarm */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
	KESO_CONST AlarmType _alarm_id;
/* c4_Alarm */
} c4_Alarm_t;
#define C4_ALARM_OBJ(_obj_) ((c4_Alarm_t*)(_obj_))
#define KESO_ALLOC_C4_ALARM() KESO_ALLOC(C4_ALARM_ID,sizeof(c4_Alarm_t),0)
#define KESO_ALLOC_STACK_C4_ALARM(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C4_ALARM_ID,sizeof(c4_Alarm_t),0)
#define KESO_ALLOC_INLINE_C4_ALARM() KESO_ALLOC(C4_ALARM_ID,sizeof(c4_Alarm_t),0)

/* class methods prototypes */



#endif /* !defined(__C4_ALARM_H__) */
