/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c5_HelloWorld.h"
#include "c7_DebugOut.h"
#include "c8_StringBuilder.h"
#include "c9_QueueElement.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 1 c5_HelloWorld_m2_printList
 *
 * c5_HelloWorld_m3_run
 * (valid java/lang/Object, ?null java/lang/Object)
 *
 * total (valid java/lang/Object, ?null java/lang/Object)
 */

/* c5_HelloWorld_m2_printList c28_EventService_m1_waitEvent */
/* test/HelloWorld.printList(Ltest/QueueElement;)V */

void c5_HelloWorld_m2_printList(object_pointer* pref, object_pointer obj0, object_pointer obj1)
{
	jint i20;
	jint i22;
	object_pointer volatile obj[7];
	/* initial new frame (big) */
	for (int c = 0; c < 6; c++) {
		obj[c] = (object_pointer) (void *) 0;
	}
	*pref = (object_pointer) (void *) ((int) obj | 0x1); /* register new frame */
	
/* c5_HelloWorld_m2_printList_B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 33:   DebugOut.print("\t");
/==============================================================*/

	obj[4] = SC7_DEBUGOUT_C7F1_BUF(((domain_t *) &__DOSEK_APPDATA_dom1__DDesc));
	c8_StringBuilder_m1_append(obj[4], ((object_pointer) ((object_pointer*) &str1+1)));
	/* goto z31_c5_HelloWorld_m2_printList_B4 */

	
z31_c5_HelloWorld_m2_printList_B4: /* Pred:  0 22 No: 4 done */
	
/*==============================================================/
: 34: 
: 35:   while(true) {
| 36:    if(qel.next() == null) {
/==============================================================*/

	obj[5] = (ACCFIELD_C9_QUEUEELEMENT_C9F1_NEXT(obj1));
	if (obj[5]!=(object_pointer) (void *) 0) goto c5_HelloWorld_m2_printList_B22;

	
/* z32_c5_HelloWorld_m2_printList_B4:  Pred:  5 No: 6 done */
	
/*==============================================================/
| 37:     DebugOut.println(qel.value());
| 38:     break;
/==============================================================*/

	i20 = (ACCFIELD_C9_QUEUEELEMENT_C9F2_VALUE(obj1));
	c7_DebugOut_m7_println(i20);
	goto c5_HelloWorld_m2_printList_B64;

	
c5_HelloWorld_m2_printList_B22: /* Pred:  5 No: 13 done */
	
/*==============================================================/
: 39:    } else {
| 40:     DebugOut.print(qel.value() + ", ");
: 41:    }
| 42:    qel = qel.next();
/==============================================================*/

	obj[0] = KESO_ALLOC_C8_STRINGBUILDER();
	c8_StringBuilder_m3__init_(obj[0]);
	i22 = (ACCFIELD_C9_QUEUEELEMENT_C9F2_VALUE(obj1));
	obj[1] = c8_StringBuilder_m8_append(obj[0], i22);
	obj[2] = c8_StringBuilder_m1_append(obj[1], ((object_pointer) ((object_pointer*) &str2+1)));
	obj[3] = c8_StringBuilder_m9_toString(obj[2]);
	c8_StringBuilder_m1_append(obj[4], obj[3]);
	obj1 = (ACCFIELD_C9_QUEUEELEMENT_C9F1_NEXT(obj1));
	goto z31_c5_HelloWorld_m2_printList_B4;

	
c5_HelloWorld_m2_printList_B64: /* Pred:  12 No: 8 done */
	
/*==============================================================/
: 44: 
: 45:   // we still hold the reference to the currently printed queue at
: 46:   // this point!
: 47:   if (Config.getInt("NonStop", 0)==0) {
| 48:    EventService.waitEvent(Events.Wakeup);
| 49:    EventService.clearEvent(Events.Wakeup);
/==============================================================*/

	obj[6] = KESO_EOLL;
	WaitEvent(0x1);
	ClearEvent(0x1);

	
/* c5_HelloWorld_m2_printList_B93:  Pred:  64 No: 12 done */
	
/*==============================================================/
: 51: 
: 52:   if (Config.getInt("UseGuards", 0)==1) {
: 53:    GC.guard(512,2);
: 54:   }
| 55:  }
/==============================================================*/

	return;

}

