/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __C7_DEBUGOUT_H__
#define __C7_DEBUGOUT_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define C7_DEBUGOUT_ID ((class_id_t)7)

/* object data */
typedef struct {
/* c7_DebugOut */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* c7_DebugOut */
} c7_DebugOut_t;
#define C7_DEBUGOUT_OBJ(_obj_) ((c7_DebugOut_t*)(_obj_))
#define KESO_ALLOC_C7_DEBUGOUT() KESO_ALLOC(C7_DEBUGOUT_ID,sizeof(c7_DebugOut_t),0)
#define KESO_ALLOC_STACK_C7_DEBUGOUT(_mem_) keso_alloc_stack((object_pointer)&(_mem_), C7_DEBUGOUT_ID,sizeof(c7_DebugOut_t),0)
#define KESO_ALLOC_INLINE_C7_DEBUGOUT() KESO_ALLOC(C7_DEBUGOUT_ID,sizeof(c7_DebugOut_t),0)

/* class methods prototypes */
/* c7_DebugOut_m3__clinit_ #non_blocking */
/* <clinit>()V */
void c7_DebugOut_m3__clinit_(void);
/* c7_DebugOut_m5_println #non_blocking */
/* println(Ljava/lang/String;)V */
void c7_DebugOut_m5_println(object_pointer obj0);
/* c7_DebugOut_m2_raw_print #non_blocking */
/* raw_print(Ljava/lang/StringBuilder;)V */
void c7_DebugOut_m2_raw_print(object_pointer obj0);
/* c7_DebugOut_m7_println #non_blocking */
/* println(I)V */
void c7_DebugOut_m7_println(jint i0);



#endif /* !defined(__C7_DEBUGOUT_H__) */
