/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c11_Integer.h"
#include "c7_DebugOut.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 1 c7_DebugOut_m7_println
 *
 * c5_HelloWorld_m2_printList
 * (int)
 *
 * total (int)
 */

/* c7_DebugOut_m7_println #non_blocking */
/* keso/io/DebugOut.println(I)V */

void c7_DebugOut_m7_println(jint i0)
{
	object_pointer obj1_0;
	
/* c7_DebugOut_m7_println_B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 82:   println(Integer.toString(value));
| 83:  }
/==============================================================*/

	obj1_0 = c11_Integer_m1_toString(i0);
	c7_DebugOut_m5_println(obj1_0);
	/* goto c7_DebugOut_m7_println_B9 */

	
/* c7_DebugOut_m7_println_B9:  Pred:  0 No: 2 done */

	return;

}

