/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c8_StringBuilder.h"
#include "char_array.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 3 c8_StringBuilder_m3__init_
 *
 * c7_DebugOut_m3__clinit_
 * (valid java/lang/StringBuilder)
 *
 * c5_HelloWorld_m2_printList
 * (valid java/lang/StringBuilder)
 *
 * c5_HelloWorld_m3_run
 * (valid java/lang/StringBuilder)
 *
 * total (valid java/lang/StringBuilder)
 */

/* c8_StringBuilder_m3__init_ #non_blocking */
/* java/lang/StringBuilder.<init>()V */

void c8_StringBuilder_m3__init_(object_pointer obj0)
{
	object_pointer obj2;
	
/* c8_StringBuilder_m3__init__B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 45:   this(minIncrease);
| 46:  }
/==============================================================*/

	obj2 = keso_alloc_char_array(0x8);
	(ACCFIELD_C8_STRINGBUILDER_C8F1_DATA(obj0)) = (object_pointer)obj2;
	(ACCFIELD_C8_STRINGBUILDER_C8F2_LENGTH(obj0)) = (jint)(0);
	/* goto c8_StringBuilder_m3__init__B8 */

	
/* c8_StringBuilder_m3__init__B8:  Pred:  0 No: 4 done */

	return;

}

