/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#include "c8_StringBuilder.h"
#include "char_array.h"
#include "keso_exceptions.h"
#include "keso_types.h"
#include "global.h"
#include "domains.h"


/*
 * call analysis 3 c8_StringBuilder_m10_append
 *
 * c11_Integer_m1_toString
 * (valid java/lang/StringBuilder, 48)
 *
 * c11_Integer_m1_toString
 * (valid java/lang/StringBuilder, int)
 *
 * c11_Integer_m1_toString
 * (valid java/lang/StringBuilder, 45)
 *
 * total (valid java/lang/StringBuilder, unknown)
 */

/* c8_StringBuilder_m10_append #non_blocking */
/* java/lang/StringBuilder.append(C)Ljava/lang/StringBuilder; */

object_pointer c8_StringBuilder_m10_append(object_pointer obj0, jint i1)
{
	jint i3_0;
	object_pointer obj4_0;
	jint i3_1;
	jint i3_2;
	
/* c8_StringBuilder_m10_append_B0:  Pred:  No: 1 done */
	
/*==============================================================/
| 106:   ensureCapacity(length + 1);
| 107:   data[length] = c;
/==============================================================*/

	i3_0 = ((ACCFIELD_C8_STRINGBUILDER_C8F2_LENGTH(obj0))+0x1);
	c8_StringBuilder_m6_ensureCapacity(obj0, i3_0);
	obj4_0 = (ACCFIELD_C8_STRINGBUILDER_C8F1_DATA(obj0));
	i3_1 = (ACCFIELD_C8_STRINGBUILDER_C8F2_LENGTH(obj0));
				KESO_CHECK_CASTORE_NULLPOINTER(obj4_0,"c8_StringBuilder_m10_append",19, 12);

	
/* z62_c8_StringBuilder_m10_append_B19:  Pred:  0 No: 3 done */
	
/*==============================================================/
| 108:   length++;
| 109:   return this;
/==============================================================*/

				KESO_CHECK_CASTORE_ARRAY_NOTNULL(obj4_0,i3_1,"c8_StringBuilder_m10_append",19, 13);
	CHAR_ARRAY_LEA(obj4_0, i3_1) = i1;
	i3_2 = ((ACCFIELD_C8_STRINGBUILDER_C8F2_LENGTH(obj0))+0x1);
	(ACCFIELD_C8_STRINGBUILDER_C8F2_LENGTH(obj0)) = (jint)i3_2;
	/* goto c8_StringBuilder_m10_append_B33 */

	
/* c8_StringBuilder_m10_append_B33:  Pred:  7 No: 4 done */

	return (object_pointer)obj0;

}

