/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __COFFEE_H__
#define __COFFEE_H__
#include "keso_gc.h"
#include "keso_object_pointer.h"
#include "keso_types.h"
#define KESO_GC_DOM1_DDESC (0)

int keso_coffee_main(keso_umachineword_t did);


#define GC_LOG_INFO_PARAMETER

#include "keso_types.h"
#include "keso_config_flags.h"

#ifdef KESO_ALLOW_FORCE_GC_NEED
#define KESO_FORCE_GC_NEED() keso_force_gc_need()
void keso_force_gc_need();
#else
#define KESO_FORCE_GC_NEED() ((void)0)
#endif

typedef struct _coffee_listel_s {
	 keso_gc_slotcnt_t size;        /* size in slots */
	 struct _coffee_listel_s *next; /* Points to the next listelement */
} coffee_listel_t;

#include "global.h"
#include "keso_exceptions.h"

object_pointer keso_coffee_alloc(class_id_t class_id, obj_size_t bytesize, obj_size_t roff GC_LOG_INFO_PARAMETER);





#endif /* !defined(__COFFEE_H__) */
