/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __I33_CLOSEABLE_H__
#define __I33_CLOSEABLE_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define I33_CLOSEABLE_ID ((class_id_t)33)

/* object data */
typedef struct {
/* i33_Closeable */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* i33_Closeable */
} i33_Closeable_t;
#define I33_CLOSEABLE_OBJ(_obj_) ((i33_Closeable_t*)(_obj_))

/* class methods prototypes */



#endif /* !defined(__I33_CLOSEABLE_H__) */
