/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __I34_RUNNABLE_H__
#define __I34_RUNNABLE_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define I34_RUNNABLE_ID ((class_id_t)34)

/* object data */
typedef struct {
/* i34_Runnable */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* i34_Runnable */
} i34_Runnable_t;
#define I34_RUNNABLE_OBJ(_obj_) ((i34_Runnable_t*)(_obj_))

/* class methods prototypes */



#endif /* !defined(__I34_RUNNABLE_H__) */
