/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __I35_LISTPRINTSERVICE_H__
#define __I35_LISTPRINTSERVICE_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define I35_LISTPRINTSERVICE_ID ((class_id_t)35)

/* object data */
typedef struct {
/* i35_ListPrintService */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* i35_ListPrintService */
} i35_ListPrintService_t;
#define I35_LISTPRINTSERVICE_OBJ(_obj_) ((i35_ListPrintService_t*)(_obj_))

/* class methods prototypes */



#endif /* !defined(__I35_LISTPRINTSERVICE_H__) */
