/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __I36_PORTAL_H__
#define __I36_PORTAL_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define I36_PORTAL_ID ((class_id_t)36)

/* object data */
typedef struct {
/* i36_Portal */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* i36_Portal */
} i36_Portal_t;
#define I36_PORTAL_OBJ(_obj_) ((i36_Portal_t*)(_obj_))

/* class methods prototypes */



#endif /* !defined(__I36_PORTAL_H__) */
