/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef __I37_NONCOPYABLE_H__
#define __I37_NONCOPYABLE_H__
#include "keso_object_pointer.h"
#include "keso_types.h"

#define I37_NONCOPYABLE_ID ((class_id_t)37)

/* object data */
typedef struct {
/* i37_NonCopyable */
/* c1_Object */
OBJECT_HEADER
/* c1_Object */
/* i37_NonCopyable */
} i37_NonCopyable_t;
#define I37_NONCOPYABLE_OBJ(_obj_) ((i37_NonCopyable_t*)(_obj_))

/* class methods prototypes */



#endif /* !defined(__I37_NONCOPYABLE_H__) */
