/* THIS FILE IS AUTO-GENERATED BY KESO! DON'T EDIT */

#ifndef _KESO_TYPES_H_
#define _KESO_TYPES_H_ 1
#include <stdint.h>
#ifdef __APPLE__
	#include <mach/mach_time.h>
#endif
typedef char* code_t;
typedef uint8_t              jchar;
typedef int                    jboolean;
typedef int8_t                 jbyte;
typedef uint8_t                jubyte;
typedef int16_t                jshort;
typedef uint16_t               jushort;
typedef int32_t                jint;
typedef uint32_t               juint;
typedef int64_t                jlong;
typedef uint64_t               julong;
typedef float                  jfloat;
typedef double                 jdouble;
typedef union { unsigned char __c[4]; float __d; } __huge_val_t;
extern __huge_val_t __huge_val;
extern __huge_val_t __nan_val;
#define INFINITY (__huge_val.__d)
#define NAN (__nan_val.__d)
#endif
